[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "47c433f580dd4dce90542b7bb10ab40dd6887897"
os = "macos"

    [[LibCURL.download]]
    sha256 = "daa14a50ce5a5c5b2eabb725fbf94bbaee021c54626878b9fb89f367485e8ff7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "fde31061f021a119793c1d39c3f141b7e9f97bd7"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "82de82a4aadfeb49922ed75aaaaed32be49ffc5e640d77446140c8deff1c3a0b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "025621e3d7b596542be2f9bc7ae593cef12786eb"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1c755e3007f8dd2288154e1ad31f13968e598828959257974c51b10323cd0736"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "97faf8a2f9abaee440e9998dfbf175913ae9ac8a"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "a6bb600ae1d265e9578b64e950192be7972137e447969604ab68efd560405d8e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bde31e197b1d7cd1be7679c3cab4dee5d742722c"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a259ce5a5edb1c30edec1bb006dabc51ba58449e030596e995553d30268f1e4b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a3e7a7969a9509bc536a70a59d3d898abc7f142a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "10d23a0900064a3a3ba94a923d095884161abf9548c0769259ee4b750407114c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "addcf1aa6d7139feeebd053907e63e0d4cb21e00"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "52431d0ac201d635976a16323c7df870b7b1ccb4e57c4b76a14916deb83c410a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bab73481be94dc1781ce2842ae29dd8725d48f97"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "384fc5a15141bec2e4659c21743ccad540bb774d27b82a444199a388ee0b56a3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "492028b20ac2fbe60a7a853809e5ee33d2940b26"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f7ee655b3c4734d0da5859836a538816d75af4851777362bc362d43dd06af013"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "7a2b646a2f4c6b5c30ee8e60c9d7a2c1864f2baa"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3afd37398a0133e467133124b01ca6247dbe4860d15d2c347985c029781d00be"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "44991c9fd728514f5163b09e5f52388418883c99"
os = "windows"

    [[LibCURL.download]]
    sha256 = "a7c2d25d9598a7af978d858379fb98b7c5a576a89bf5cd89a938032dccfacd9f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "e9232d0d08f179aaca35f2eef281df7b29bc9b84"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c461b893a3c618033f7f7b627231e50dcba30b6011768708a59fc833ced0a1c9"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "riscv64"
git-tree-sha1 = "2770639128886e53f156f7329c2035eca272e534"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d4edb7e3ba838d71c9720628a06102e33a679f1d3e2942230dab3074086feea1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.riscv64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "ec7c2b898d4aff4ba2ba9b8c34763f87d515bab1"
os = "macos"

    [[LibCURL.download]]
    sha256 = "06f82146505f3e679bb7d871bdcc1476708a482c5936c43cb8e7867d5420170a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "0948fbb547d508eca16af31f9186c4f0e6705f0b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "dd2efb4c1eff09d19213ec59c5bb7327591778b9e5d34b6c6ad7f66e1a4cd645"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "2a2b8b76873c73a4f9dcc0cde7d46e414ae26ad9"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "8af7160041433933465ce34c8fd2d3bbbbb71115b5dc55e8eabeb8c997ed0862"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "683fa1edae2b6dea4df572b1edae86099a86d51a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4752c4798bc4539c7326d59e0bf9bf66655552db8865d3aa64b7e5a9b7e833f7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "82f675a2722f0bb9bef117642a083edf39cc13f1"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "fa992d7a646a37eb19f5972cce36e84b2914f7f7e242b08ad39e368320febfe5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "20fd985e5c3c017b82d6eade087d21e32c248bd5"
os = "windows"

    [[LibCURL.download]]
    sha256 = "468a284c3d34307a5a43c1cf21eff64d5374a03f41b6899e31fa0e329be51a3d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+2/LibCURL.v7.81.0.x86_64-w64-mingw32.tar.gz"
