[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "07aa38a1d9d11b54606ae94bb05b43497686669d"
os = "macos"

    [[LibCURL.download]]
    sha256 = "e715985b4fde60195a75db486ecfe72dc9bf888f36f18453cd82d7c016c459b7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "b088e9ad2b476b139d3f716c05120d745657c3c6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f1ac7a51fd24740ee07071b899e2edb8f6ccccb6e077a3919e6b5f9ae0d89354"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "61e9a6a76c57b695cd5ad540fa24d6548b95b83d"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "cfd1bfb76d7514b6a09add8dc31a8a783be5bc227c6b7570e7e9515feb2386eb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6df47edad8a59b1a3b34efcb1d77f81fb3b092fd"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "becb7a954f0bee9825040f03cc5080176b83ccdb4f2426472cd223deb466f59e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e8d12e8cc8080e2acd9fa937fa2e4988c1ba729d"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6f1b52439d0fffed2104d95408a527e731503b47b044751f3e9a5886592c5bde"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e1b5734f3fc711faaf353380c29bcf03c8e02f10"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6128563d01cb3ffbfbcaa280b757965d8d8253e8416664b1558b33335c4dbab3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7709716323d21ce416177c0254be6e5f6b775664"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "37addb423052abdfaccc2d7db35ba9ef58b13e7cc9e9bbc2c688e0f49ea9a976"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "ad48bc0ef8f505fdb417b91603b5c98108a951aa"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "574cadd57292f83b19d6675cfa43656b220ae2d4b804ac4d258067b0a94ea582"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "a6e07f3d1ef58a18133e78bce9d73f2bab03047f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f2f3365aee93b20c45e97105a2b8a7d358f8578878e7aeceba445be858db4d84"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "26de6a02c2dc28bea9048fca276a4e84b2de7d09"
os = "windows"

    [[LibCURL.download]]
    sha256 = "820deb94b07b019568613d96c2c77918e12350641d863e2f7d4de3021c859b65"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "906b2d4dac8fadd9fd25633f416719f98bd88008"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b4349efec07a4360d2b36f8be637e5cef8aa7eca784d25c05bee76cf8d26e6e3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "e95d9d3da3aed8aec2a2430bb6c2ff07ed7553ca"
os = "macos"

    [[LibCURL.download]]
    sha256 = "c179ecda968090db6256509608937504c2e60fe6e5dd3cb63f6f754ab9703203"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "3a6f843d0c8e23db838ba9e952b86eb260b87eb0"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "bb18b512d3886f92deb80847f14ca7d449fa8a44ec5d6a42a2ca129e80366a7a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "288534ee3358bf14f4ddbae8222c5fe4bac216ef"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b154f0a51dae6a6405da03ed1692ac71f5f6e9835850c85c6abf0768fa72b679"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "bdae371a88ab717170c0b98c1ac5c37be613fe42"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "81201e8a8487b471d22d684e162eb3a384cf5f818131cc1481933ae812d9f42a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "af81a3c836ab2e3844adc750c6bea33590a56d97"
os = "windows"

    [[LibCURL.download]]
    sha256 = "562e128a4d5ae1e1b2c3013b089fad20d0dcf5de43434700b00adba85ce17bcb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+4/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
