[[LibCURL]]
arch = "i686"
git-tree-sha1 = "3875f2ebba608a9209036a103c5291fcae28a27a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ff1ffba50824f7e950bc93fbe9180d055f36655c512b0cdc36035cc32e69633c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "fe462f2139d5a9f7912f4851ad55c69cf9cd9ac9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4af7cfced9896b7da44bdcdde5a299423408a3b7cfa139fa5ce99534c10983a0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "b27879d08940ab4717c6dd2d06f5fdc659ab7c31"
os = "windows"

    [[LibCURL.download]]
    sha256 = "3724348e116ee32c92887ed09caa7627a5176ba526d60c31c2e272ea16751108"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "00802f9a8a7cef0aa5751ca363507c3fc07de490"
os = "windows"

    [[LibCURL.download]]
    sha256 = "a6ece7cbcb7f81e5c8f2f36c8fb5be0906978f5f614e2be2880e4d1dfb66a22d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.x86_64-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "armv7l"
git-tree-sha1 = "3958a5fb1023227ace6f582a970a89d03b50a756"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "cebea1a70b872077f2675697c478200043b4de8e82abf6e1c66e5ee3a6793651"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
git-tree-sha1 = "420128ea83afd37219aae3c0e048261ad04868be"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d75ec17dab56c74f74aeeb434a6e736e1d188ce470860abb39360f051623e99c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "0dd51b47f860c98f1d2dcfc43506219e8cc77a64"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "bb62a40268ecdac066d7efbaade56976aafe09ad23358137727f09f389fc45bf"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "904600d991a748e89b4272f20181157c1bdf0d94"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e5245329f781e7c2495383403ce489d984cee24801b4bc6b9f853124e6df083d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "34bbf66e2645d6e8f7e6441928c6c24828fad44a"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "17bc2e8a3ff006a47044c4c472e437d8f615dd7cbea6de3bc0f2f17ee2c4e481"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "95c207438ab20edb150507f35562b679d173bb65"
os = "macos"

    [[LibCURL.download]]
    sha256 = "42c22f95c87429022864002dfccd2be009d7a5bc44aae96e6001df3d8b249d02"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.x86_64-apple-darwin14.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "d9e9995e46021ab57aa52ff9c1136d6b168dbdcb"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "20e16d6d8d6998b1ca4d1dcc695d964e13ae14563f884e78ee93b3ee784b5855"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "3a73a3421cf14b18b13baf843e9ffa0b8645ada8"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "dcbcd7a680b724fafb8c49bd106444b6c9046f36a848e981cf48beb805e29e8e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "1d4080e0af84bd1577f23fe360c502ec3456ab70"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "50afd2175032fcb6ff1cd00fe5148dab7ee20dc89578d1cda8524c6e07c56c9d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.70.0+0/LibCURL.v7.70.0.x86_64-linux-musl.tar.gz"
