[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "38b78f7fe2e98a4a6931990eb86f99daff4d9f5e"
os = "macos"

    [[LibCURL.download]]
    sha256 = "a59e352d3100b0aad7a77a2352c5d8d5e1c0117e75fe38a1e02d771df656ae06"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "7892d848a69dae6b427c85f7a6c086c1f91a6114"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "beac1ddccff41bb29092c2961a7e86bd927508f0c547c8fbfd7daa996fefd7c8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "99a67230068999f6e7ddf424f39627accbdc464d"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "89a55f7ff507473b7995ab9f04da4384e2bc0c10333fecf7416927aeaab80d3e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "47129017aa846326c79156fe8815b86c8fcb9f9e"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "343c0c31423fbfd0d675ec82b38f1f62548a5ee7b036c22c708170d54a42f2d5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf28745a0900eb35b9addbdcf917419f476bc007"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "118dbf13c4142445c4a4365c3e4b4ce8311f5e8b7d4dec420d0584e0956605b5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1912b7227e53b1b9ff1c727490118452d53e43a4"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c4764febf0ac006bdde995dee5619d5c8c654a6f357f70e7b7fb524f696cf7e5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54a5f7d1dd0cc73cae8b9cafd32300be67d73238"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ca79b7afb823e17b7778ce7c6cb33f240eb52fa3a9243dffd640043718c3848a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "4d81230cecba8848aaccc033f87053485b152913"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d62bbf27fa93419e20dd48a0c36b425bb3a6a068e5e19781fa2f06a75a427ed0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "032cfc030e9ec439e51586e8df17f89e21f11ca4"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "56302667a7feee5c16eb56423feb782ed38b6033adcd896f641f0caec51bc505"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "76145cb7be8b1abf50e873f8857ef8f89bc12a7c"
os = "windows"

    [[LibCURL.download]]
    sha256 = "f821b449d04a71074d914a16b84d3f18aac9bc4d9f966fc8328e6dd92f9d230c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "bb8a7c2d0446dc4d87392ac67a55c0bd7013677b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a5a40be6cc897b8e8b4e0e98eadbe3704a4829f2755b709300388630a7fdb52e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "9e500e706b7e1bf62b82aa8bb2ed155f06ef25d0"
os = "macos"

    [[LibCURL.download]]
    sha256 = "2d15a5ed63af1368d5a758116e27a20e9d1051408cf2e50aab51b437f2620f6d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "63c59cd6ee59dba377bc0fcaa506208c7cf63b4f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e00b2c166c740dad4eae7b1d89c1c419a0438a101fcd39aea4afeb0ab205360b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "1494fbfb625243f4dc52ff1a525d9af26f46a622"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5231329e253a65195c97791cd3f11b58cbb3258f548d8586bc37e29e4734a9a3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "436599aab6588d1cd4f844df910e576d70aac706"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "a992c6e01587d8522a67f036cdb7a50e1aa70d425ee20610170298997b178eba"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "b78e6c0fadc5073bbdccd087b4d72730ff18642a"
os = "windows"

    [[LibCURL.download]]
    sha256 = "735b40e546c047d06d985a6d1bd7211adedee3e4ad7d0a7e8e30b4b9da3388c0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+5/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
