[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "e4e150004655a824a9759071cb8fc83cbef70b5b"
os = "macos"

    [[LibCURL.download]]
    sha256 = "d86f3b026d40ab359717abeb183f14caaed0ec366385ce4a64098254affcaf05"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "3252287819b5ea0e8d33e980a1eb6b3ff51ccf24"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "02c3214ba14d8f4863a6cdb0aa057aee55b8646f8ac407c7de43a4f0beadca4e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "74f5041e818b6f9d9db7c3967b25eafb1597cf31"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0b916cc73fc0317f7cffeac44d358fd40c3f58c35a74632628d61ec6a5038979"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "b9e542a4570cd60f87929f8a4e27c3bf468859e7"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "031fea0e0160f893e433fa59cae8ea7d7e7b2e01e7bc966c9afb7bf9e8ffcda4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b4cc17585040bdec10e4dcf7db898884d6e2cf0c"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "20c8d2e5951f91f9efc252679f5d955af5ac93c0c030e5bdb824d3a94ac2df3f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "77e408612d726ef5c635ab92a6c7e25c8e21715b"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "293583ff7f7bcf60bed1db57996b93ec75c47c4f198890644674088fed9b8e5e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d39a40e4bfa1665c3176ceea3d0ebe50cab5a4bc"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f827c8fd0bf15700196db06f3b986ecb5950e467724cfac38b43bba762d84a8a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf00baacfa76e8769ee1e68198d2dd8e0b201071"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "2009cfd9d7a7328e26dd7f2112f7706893a3993ff7ab667f98d451c96f9542dd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "b98836ba71c943f6b49a5ce7a21dbc8eadbf5dd2"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "30d4450783fb8b9bb8213def64fb571ac9628ff7598a1fef9b036c3746fd8bdf"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "ea7b970cbca97f5d06457fd94cd8d88ad9e612ad"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "dfba5d7236092f33e605f3d82b7c8e37d9ca7361eebe050d9f23857a82cc04af"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "02784cfe19148836a362ce1e760ff5c56d2f6328"
os = "windows"

    [[LibCURL.download]]
    sha256 = "eb4a742452660864b2daaa979630ab0d24013294aea4a560fff3acb220ddbdfc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "e93bfe6c76c6639bbb850fb3e6743768c4f1064a"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6ab4cf042eb996f8c8f1a918f5616f86308b3b983c81e63cb653cf434bc0f28b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "riscv64"
git-tree-sha1 = "8b38a84c4c29eafd73783578d6f9a58c05c76cb8"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "78007eacfbc439770f3d1e888979a9a8ae9abab02731fd7f572c1f5f4b979626"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.riscv64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c8554da36f14b4140f67336d4b404a799bce9652"
os = "macos"

    [[LibCURL.download]]
    sha256 = "9ff3d34ff6ef5718ff9b4bec2b910f94fc07c8047c41628912dc9a59e06ca5e0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "820fbcba53db54b86b75a94edb840528e09f7840"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "238a6c52100cf2a403d4c60cb3db56a075bab976d02666d2cebcb7858f1b9e1c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "1739f31f77b04fd29cd3793b495f05598467265d"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "a8e94b22a40d8cde979a67c75c10f3b9c8ce6da9ec16cbb19db4dc53cbd62806"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "fb9962dcd3331a12013b8818e633566752cf35ff"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4b1164cd6739d912804a33fa007818b77939bb898082e9f47fabb398c0164491"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "b4ad9c32ca7089ee04ff6c585b6427597c78819f"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "8ebdbe3abef0a2c35c6df06e9190b6fda1ddf73802ff5b83540d514c1992f57f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a69f118b25a2376914d63688ba9b607608e4f214"
os = "windows"

    [[LibCURL.download]]
    sha256 = "87ad06a054bf65c663c754a64d54487fdedf9938d1d8d4795bed8f7a139b5c3e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.21.0+0/LibCURL.v8.21.0.x86_64-w64-mingw32.tar.gz"
