[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "87a0a8bf4b8a5e8c0b1fb6d3a0825ec7b87609b3"
os = "macos"

    [[LibCURL.download]]
    sha256 = "a0e3ee51ee1dcd70729bad2f7e4e90f7607faba4e5bbaaa402f065ea2a4593e6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "2ab112f84f3a0bb5d95142822618d06087e578e0"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3474b5196f7905cb28ddd55237bd0e153d4a30da627daee86b6fb61873511367"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "86aceafead5babfcabb5958725d7817ab5efe6ec"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d5d7a15a25a9addd048b474881943ae0badd2898ebb62034b84701ceb3e80e04"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "21253274cc1d048eea75c8cde5ea24637de09344"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "2fc5ca3ac7bfb0d252fc698d4ebdd45c98bbd23db7854d7fc97e07e0dc1083d1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "03f8fd13b0723e42d55a3284dae166a3a2a29f04"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "2abf41c6f267c4aaadddf55481b2dfecf038b5b1fcf87000e4ef2bfd16637964"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f29050b8f4bb76ba26f43dbfdcd8ca08806be3da"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0c361e6f9eaa236cdad01f0fcf9abd132c050741b99977da549b4871175686c7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1fbf21eb601915176b95f146aaa2554ace95dd59"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "96e1ba9d5d13e5978502df3b80c803d8a79749cbb55302d6c6396b35e1abd394"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2d505659fa68e53fdfb203535da97f376b7549a1"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "45d4acdfbbdf15462c2989b3bab2185f40ba00a169c03251d86c525a240674fd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "fe9fdb1908c1af06a5c1ffdccbabd6414026e82e"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5f83e37524cd10028c11f1b4f0f49eb5bc87888d3a5ab683c3e8151b20fca270"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "9d64ee775317da0f530418533df27498e2f0db3f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a0329c0c725cd8d18ce7706e16bb66ebc36d2c8130b9c494e7bc5b4a43e4004b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "81aeafb999911efd40eab30b6f51dfc2f5c07468"
os = "windows"

    [[LibCURL.download]]
    sha256 = "910d564a7a5c52e9b3e0c36eab286dd5558802a8e37643a2dd9b4ab09524b1b1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "a18fc5e898153c2f95d815ea53be9902113b12d4"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1066c99a5be391df6c6f6d0cd81a1b662106e813e3da29f3093948773aea1a64"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "e4981c34f18f0b3349139221154c32518f8e2534"
os = "macos"

    [[LibCURL.download]]
    sha256 = "c6775bcb49ea270aa006c5c09eaa6f0394bced3853f7a617dc5ebef1c2946d84"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "32e093665053ae692bba98cff9d0cfe6557a7d20"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0e952396fff07c9c5e23e51b82eb2750245c06400f81719a65301783f48ca076"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "ee5ce7937d92c1cd95a4d91badb47f7a09597a30"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "6f6c082c569bf2300dd256b70f03af5202ec14287173f10d2ebe25e861326355"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "50b0a37e3c68111eaf6a18eb9c31d9a63e4ad407"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5da090fee15c339de0b5e08a60c72761b060554105d057fe168f42f431b1cb0e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "fde6df54d70b1d02ab3326f727a8db638324f4ae"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "af2d515a3e303c1c7c1d2f06022a5fc03178bb04fe91b6f4aa87aa58d96fe005"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "076b07d29591bbc91f64cccb506f73d1d89c68ad"
os = "windows"

    [[LibCURL.download]]
    sha256 = "1b3c95fa5b814912c7722a76070a9c440e85dbbad689984dab173b086e3fb9c4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.1+0/LibCURL.v8.11.1.x86_64-w64-mingw32.tar.gz"
