[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "6c2634c05b5c09d8aee45d52fba818f25946a018"
os = "macos"

    [[LibCURL.download]]
    sha256 = "0ca567054255407bb2e8039eb1f3d7f2203f4ef5c865400539e37ee0a1ccc0bc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "28ce4ae276ff42d3260afe2a8e1ca92c62bf0ce3"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "2730ef7994f2cb1f7eaaf2d911a4df022e08a6c98a6519f1ec7e23f124a84b38"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "0dbb644d1f8eb889c5a454bceb92fbe376a5f9a1"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a46803461e720f0ff4668080643d58f99a984ff5144ba918cda65ab1183871b8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "199aa1662e582548da5277a1df1b3151bcc14336"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c1baad7f7199bb072b52b6e4e31979323f344196fbeba7d1e3e55ef086f0f39c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "69c037c9b62196b6f95bbc6475442b8caf9967c4"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "cfea3d85598784042de9f768a6169500707db8c35e83f68bc38133da7e3982b6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "08d61cae4e407860f939cec491bc52e88ad7d55d"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f1f694634945602abd887494b2bce20a09b7f4cb09058291de6b0b007cf50a80"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "35e45eee157cfcd2528df7200c7059b69c69d57a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3809f75146fb7e675dfe229e90b265bf21fdf56a8593cb121728f1e8dfbcc535"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "a1e9824c908589771ad11cd33d712a84c704a050"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0134524cab5d34fea4050bc488b2cbc4e1146fe75a0ecf4ffdc9aa1f636d8c9e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "cb78fd7e9f8c6258e1d026bbb973b11f48cc0239"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "912297fd081cc72a3ffda8b6d2fdf62ce4ca9e0837379d790a804f6a92da4294"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "27703f9b1b515ab0fb8235a515bb0b3404c6ef71"
os = "windows"

    [[LibCURL.download]]
    sha256 = "9a1a8ffe98ef60a1ee4978d20b6b1ef4b5033acff5ab0a37613c5747e2952481"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "61d39c0905aab3e42e6f24cd32b3c9f7393b1a86"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "15dec644950f1bcdc7a016303d624969e47ce93577f652f556e8d85d8c774691"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "f1ee1908d2475ede64fe045eb36fe4f0f1cabcb1"
os = "macos"

    [[LibCURL.download]]
    sha256 = "f232010ededff2691edd2d8fb2cf0b059341aaf0c849ae209b3267b7b335a1e9"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "ba3dd5dc557c3adf4a9a5719015e3b47e9c758ce"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "151599808160607ed940cc106b168442f01e6b180466f601563da2b6bbb8c555"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "2350c567b32d0f9859826780a1d438ed8cc681fe"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a791572b357a16aa1909c9f5a05efa1f8069e8a2ecbe3962569e746ff17a346d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "78440fb10d9881f31248074998c7601e15aa2f5f"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "183229cf4182fee1e7f5929eb762b6ce4f9ea53135cc4b60c3489bfd800b7f61"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "5c3e484bd311afd8cc08fd5d3abbb1194e9b2ff4"
os = "windows"

    [[LibCURL.download]]
    sha256 = "913dcac149cdb0f4b0d3d8dd991e742195254abfeb72505bcda8ba8a898e48ef"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+1/LibCURL.v7.81.0.x86_64-w64-mingw32.tar.gz"
