[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "64bd57871bca59a7d6d260a1653d69edbda842fe"
os = "macos"

    [[LibCURL.download]]
    sha256 = "66b3b92f937c8cb99e217f2ad2acc3dee70d0781560239dbdf4f7a2a26911b20"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "d1000b88ce37dad417d56f8f515b8874b5fb6883"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "602cfc400603772ecc645ac0b6f7b94358b7f67b0ebcbd5c41ebf7d849f3ef41"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "c6d28acc831930719b415072bd779e5977bbb2c9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6afefca65d75c52226d5a0db0fd5102b338f4b534bd1a09137953608152f8d6e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3e68f556add7edc33872c13a60d3909d19818d6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "017d96bea1128aa4fc8ea670b5835b990f4ced9b954f7122be76bc55c0a17684"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1c800bcd34a41170f62cd5808992b0b4b120a583"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4bd944352187a0f4132b3d88e34418077b375a54f782b37f7bbc5099836798dd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ca415f008ffa991bc5399a33090f15ed63e5a678"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "217150f1fa3104caf3ec7da41a4ae1b0f360ee4ecfb0492e8d6daf46e09f5c54"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "84866745578e9d6d5a71708a5cbbd5587a7ade31"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ca6e2b48c7289c025eae77b071dd0700a6d3045f17967fe7945101f14595d5a4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "9582de18482bc66c721d14a22c4de36607be09ef"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "256094746554c6f166f62f7d5a46fa9bd810c0c6186866d028cb479a78e29fdb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "a7929dba8245427fbcdb196bb977d9c302b5bc96"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9cc6ee54f90d46c5e2c59d1e83ab6a171d1d6d4d563e4b733b73fd0704ff2935"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "1cb7792b79eb84af88d2b05a87d9ee3882bcb087"
os = "windows"

    [[LibCURL.download]]
    sha256 = "23626bd5d7bd0f1258137ffcadd33bd50acab6864ed1b5bee42906a3d17f5977"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "ccb6680360396a8e82943338d4fac4a5b8406821"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e0411a3d316fa6c5a83264f75a8b95aa0a628b2d01f5f498cd20de5ad9591069"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "d95501072c2fa3a1a9c047205b761fc2bc092cb5"
os = "macos"

    [[LibCURL.download]]
    sha256 = "0fa701e8614b69361953b7de603c4980b5a5440b87adc6ffa7a03277febba133"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "42205eb279ce9a78700958e011e1d8343d5f7975"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "32579086e6f0ca70e9ccdcb559ba4295714e020ffc395537f24d4aecde8fe034"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "b0b23403eb6b2e26a5dd7edb1c7c6978c0dde84b"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "bbd1d68ac48b55ad0b551d88c5055ea4eaa9d343f968a87f1f41f2400ce86601"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "eeedd4c8067fa3d1a6cadad0875bfd1cec284cf3"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "65776c039eb96c6b8893c59348620193032e52f1945f93cb4daa3a4043d0bd31"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "68eef2a1dcb032829c17c0e4c859768b5f082f47"
os = "windows"

    [[LibCURL.download]]
    sha256 = "d8e0909d809a789d428fcb3772dd24f3400971c09ee619fc888743764363bda3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+6/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
