[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "f219fd2ac288a4c0c6b47a0e33569d8868d7e9ea"
os = "macos"

    [[LibCURL.download]]
    sha256 = "995e6af9c16412e1441d8d5a14b0d0ed5dc9801793d7972aed5fe7ee839f1afd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "dcaa1a31b9728de3243e80e5c42e13dae638c39d"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "80dead8a2144f60035bf01bc39b572bf8e7e5f1ea0b2ceb6a4c094150d094071"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "e7e17f078d12e2c9f5feeb344eda1ba26080de37"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "61fcb921fea2c5a2dac8012d3df57401f405584c43e011e3386cc2a690086ab5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "916cdaf2d9cb5fb7aec5e9abbdb1ccddab1f3e33"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "ee55224ed7c2870eb184d72a64d5bc228d59d1aea9233792ac5343895b825af0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a8e45482821d81d597b99625f5e294f2d4c2574b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "22a552b474b2d526d4d02585dfdf666aa6c9820446ad8a3462bb9b55f9505151"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a0d2fc9e5e347c8fac29659c4784822943dc914"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f8ab81806b3c6ebbc895d1d153b268a5fb874da539f031639fe7e5421d440518"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0e9a3b6b3153b835f151e1a97c94789ff2b6d57"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "7240a4e4673d1d97bc4b3f50b32316584ed95b76ed4989928f63ac8de58d9863"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "707af31d61446eb56b9f1462e37b131fb1d7cd93"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "51b6feea5710f093aedb15b21d27bfb73ba2fa327c2f4b7bfc2d0e0a5a3e93cc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "635ff514562994f9ee90ee28eb7903cb10f9118d"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e261c60f03e81fb984c914a8aa2c9eb57db0bb629dba9df2216c6900f2326d76"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "1afbcf37945cfa455aecdcbbbb2296f90fb5f40e"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "2f3cb08b286b7fa87e0a0e9e1778402f880ef4a7146c5a605cd6fdc1b4ba9a1c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "1c0c42acfede7c4ada9d1e3cfd8d53fccdf36f3b"
os = "windows"

    [[LibCURL.download]]
    sha256 = "c74e3590ffb8f1db06ce56ad8b291e74f103df87244b407c796e52709f98a01a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "dc4f517896aad0ed2293f4b99e7942ab8467d8c6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0fd5935385d414a6b13d0170e7d8547f1822c181d238ad6a525dc871835fcb1b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "riscv64"
git-tree-sha1 = "73c1840830ee585a3a32326458bfbb307c8a459f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6623b4efe2469a3a3ba4171147a6e05540d0caa3a17f3b420ca6f0ac80faed03"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.riscv64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "0adb6e2e7cea1feb090a706a5c369c8c7ab72f0a"
os = "macos"

    [[LibCURL.download]]
    sha256 = "7c6c3b031dbdb6fba68af41e54df6f904025fbb9971073e907077dcb682ab389"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "f9afefef46c115974a6391151d09bc93d449065c"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "12203d12cfbb3756d3d20e2e3938610d84d9771b87a672e82b8d3f5b70c07a67"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "1732a44b83307eb78df084e8909bcdc919527dfc"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "06eae80db7d6735c3024c18478030f0452b09741452fb5b0a500dfc030a1f3cf"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "8f2c8a48bb04b93dabca72362658b3317e873b01"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4f54ffd6f926571e255058a47330b8d0f6e55084dc96d08c69120ab9ccc1a204"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "b741b943752f37a2a4eeac9333d689565ad626eb"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "10d6b53b25e6277dd29f817e13280eb02fb7728cbc712086307c1be68e4c463a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "78bec4749ab173dc7948f373ac8e71fed6cb7fbb"
os = "windows"

    [[LibCURL.download]]
    sha256 = "797cbb3ebdecac57860454fe0b488d1a2c7a365f83bdd5d473027e3fdd9e7121"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.12.0+0/LibCURL.v8.12.0.x86_64-w64-mingw32.tar.gz"
