[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "7a3bd03a1876b7a1dfbb5275f300b65460387ae5"
os = "macos"

    [[LibCURL.download]]
    sha256 = "49b5daf0d122108d7ae7c6c02f9a5596b4b5614dd17c5e14e460b0f88986af89"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "0a94c000d2ea44dc6b0f4bd0ca6995b8887fc945"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "58fc3fa612fa21b94045cdda6439abb4ba426dcd128efd4a1980aa49e5d1ad02"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "ee247c420da545cb092df42ce645a03a338a3135"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "89184b1d7067eef096715009b7809c37c210f847808913d395ea2e5108634d61"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1fa0a03406fe49b1b461683af64f266910b906db"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d4565aa13312dadeecb1153316d555e0a0354a509236eb5ff26223f63af5ba4e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24fbb3c41d6174f752933b890b03f2be03627c0f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c0df75557113e052f039117e053e4293424800fc780476e937d1f38720bb876e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0c25e6d103dbcec8a305aa385eba7d5aaec1a22e"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "565a06977504c60ae2071dc203c53a0b4f3a6273081a189da986b5526c34bbd2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac2ba902afff320137c62e195225c86ef9d50b4a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9297db02538945b6cdecc0ee00458316a939f9cf6f3c99b0d2c15519882dd067"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "6d5ae5b03823ef37ffd5a08d929f74600495d87b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "40c2087ef198410b6a0455f14aadb24d354c7bf043114c8122ed9a08866e5584"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "0f708ed05dcd8cb0ad9ac664c126a2a1951fb6bd"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0b70087d59c1beaf35b948aa1b752fa3d26789151204b1a66a2b82d90e0630a6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "a3cbfd011302a8054d077f1b9a967cc40663c781"
os = "windows"

    [[LibCURL.download]]
    sha256 = "7312d9d81bb84094fc66f5105be517919c02f18113e24286b6be0d92a616ccc7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "8db1c9cd5e2b53da796c04a0ca85ea65078e022f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6eb1cd39f51eaf2d56c5445f690e6cea8144d55187e6e99254193492b0d86234"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a1c17e87fd27c0f1a0f4213a7ce243c22d31f2e1"
os = "macos"

    [[LibCURL.download]]
    sha256 = "a7095624d633d776246dfd536cbda5f8034382e6a75724c6f274e098c75b9df5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "bd37b0e5e47a491a54042572ce3f4c3ed12015ec"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "34b8118f95a9ad3e53d8eaed46ee167701002750dceda196b4db8ff5d27d3a9c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "e4c4c43e96fcc2d390f78d975ed2451f311b4a93"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "30d333155cfe4864dec1fea3d22059b908af2a2e492f53a7fa3efd6bcd624d65"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "bd274463c33f872a77bc447af0225d966e099153"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "365b3af90f292ea7f786c1063b7453503081180b5ee8e4b6646c5ce1362b6cdc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "54e7efb09a962686f8200b7298f51646c2fb51ed"
os = "windows"

    [[LibCURL.download]]
    sha256 = "3855aa6bf26ca961b89b7636b0a44bbe75fbb6ade5b13d2851db74a30d3f21f6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+8/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
