[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "4979ab860693f7f3a2a6b409c5ecc622a55a54c7"
os = "macos"

    [[LibCURL.download]]
    sha256 = "d451eb54dad1040e62f157a6b679e15ea8f34cac9f9e12a798cc83d4f395514a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "fe076182d8c2d63bb019dec66c4fbd82c8c423d9"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "28bad1a09fc237ec481bc7623473bd66e247d7fee2bc87b7f5c7695d3aa96a48"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "ce987a0a502ee378d3103d5fef594ec92b397045"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e7bd499b3876e2d9ea50f2fe1fbdd67a1a53116acf2d22bdd46f09b70270833e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "a3ac53d2ec49fef015d6d13c27501cf48b276ceb"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "d99c53b779b2cdc099faf1cd673dbf2217be8cef7b1efd966ae39706e7f5c4fb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6a4176155cb3fa9b0e04b3800cf99c9cc1804627"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3c34324162bc19f477060dfaf98cfdb0f942b132abb0261ae8ca48347477e45f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0a74d1c7e3690047d11a5309fcc6614dab2e05c5"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "01009d8fcd6b268b3fc032526fd0259040198735e86e6b12b7bcb1e8cd36c1a0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "86d2facabe84b7e87a82523c7286251286572522"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "2bbf56dc67bf128204b53bc6b633dd26ed07e386675e1b3f52a2a84635527bc8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54e606259c5d5522742c171959744945f029993e"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6affa623b5fc85e5f8e45676179c3e36aefd22e9a8186b776c7c3886fae0c33b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "52b6340b23418f6bde8ef5aa45c9dbbf0ec28c52"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "94cbc017418a0d4d4041dc3a606b320f915614822eb932dd0011a4c3eb976b0f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "3c407715276424ff214cf6790fd854521dfc2c03"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "67e9d97658ff7950c7d7eace11f0e9499afe4793730223ca2ef0e923e4d64e7b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "5aecf229f475b5e90a337393dd7c2a6da9c240c8"
os = "windows"

    [[LibCURL.download]]
    sha256 = "b75da2a42b15a086814004cd17ec41434b02fcd9ec2f8739318827571d316d66"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "690de4a88d38b946433f940e46bf3066eb9f9783"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "8ec15246490c09ff92f849eac6ae06bc73ba5b0f0260243384f2383c09f70461"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "riscv64"
git-tree-sha1 = "82077779e9e48e6bbae0f4c232ce6c793fb41e9b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0b4728480919e7bfe507170d56311bae18a8e6d8380f7ab51253b31a9af2c61e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.riscv64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "97d50fd0e28411b2f6b274dc01cfc8ce14d8c9b3"
os = "macos"

    [[LibCURL.download]]
    sha256 = "ac00d9ef565f339acc5ea8246fb5e654190f34b0e67062a47fc17471bdba19d5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "2b796b34fc3f63a1e08bd5aa692b33addd3e0296"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c9e87a573143975d71711850edf62f62c41746fcc44b6b09b8e23fba88173c8a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a17679157b9283472c58920a48e4729bc3609d5a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3edc41b7ae31eb3b08962be837ec06788abcfbf39ef03988e0c752d66037200c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "fceb4125885766930c88e4f1136d94630972e704"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "6d1a69dcecfaf3682a97d731beefe787fdbb9d61c966c3036ccb5846554e7c6f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "2a5bb4b41bdac87df11baf304d989527e0741f45"
os = "windows"

    [[LibCURL.download]]
    sha256 = "097b948828fecacdb3f95e6611da6d6be45879dc89c3f0757af0c7f6e0ebc55d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+9/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
