[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "05cc8e16ca6eac4f2dd4a00c328c0f18769d6ff8"
os = "macos"

    [[LibCURL.download]]
    sha256 = "8e1d862eed1999c69df45c6b2bbba0ae62e8b8232c56d63b3a60ee6bf2ab8c9b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "2b65d37e47db3deba7dfe5b2016885246480b358"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b0ccc8f26d49c6a428e4617da8d34a72410683c19bc67ac9fe96906f58350496"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "337328db957e901a880dbfa695fce72d9df3ffe0"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "413ae76313ae6a2be96d3b085b4459e93802f04382436ed7909ddf51ef180787"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c58f950ff6d1c0f36d898d5fcb732c901de3ea34"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "10f898fc9ddd278d6c162772949e8fe55c04e3b1adaf74361bc835a0294b795d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6c85ba1a03e7aa83023150d4887d4acef2d6515f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "bcb84f0b3db85e77ebffe5c3c6c4335bd702c25bb7bc20402bc7939da77dd599"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c2e534d996fb2e3e51bd297038e42055b13ad49"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "48d176f64a948de4ea7997e82adaccc45e400f8e61ef8ae8ee597eb460aa5c06"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2fe9ffb030da40956ecfa16786f37e80889d8987"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f13cb393ebcff6f6361439612881bb8318d2a0f51ff852adc72bc572e11195cd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "13991bea117ece7046ec995e4ec5f1c1d912b65a"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "fc6ea70d60e57c65bfad93b247048e6476f649824657edddb2c84c383dc32de6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "e644c103c73ae1d8041e88ebf655450a434b835c"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b898d3b1c3a440b874ec611b2dee6559ddacd3af97f7c1375a9d252db93bb9aa"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "7c3437441ed13233d11e33654d897fe9f3fc5de4"
os = "windows"

    [[LibCURL.download]]
    sha256 = "811e61e25dcb99583ac89d08c649609a52d583d8e9a620958d646a638136cd62"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "ce3e8d580294383f1682f12b10d349b9d33ddf41"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "76251c0c2df64fa11ea42752cf6b66c738aa6b068d237236896736c6414d4488"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "088e1e68b9195b0d73e20a89d0b2ec77d20d7972"
os = "macos"

    [[LibCURL.download]]
    sha256 = "d15c348795fa1d0f5274e515f4559e26c94355a5dd8d6b2264753280e24a30ba"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "02505288c3e9bf0245339d05a2969b187e2ce8b7"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ae83589c5cc4256a6f1d0d29313a6fa059ecf7cb20935e01dcd53a2e7fa4b1e3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c02107e98676c42c3ea4501a453fc6d58b7187ef"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "39c6d2c4966b590e4569304d153e6a45684195defa78a5c790ff44df3682a3ee"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "680ca2a609d14ec47523867165eee0f12c545c3a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f1e9977306cce8213ce9ce135875468fce2a5f688b0977e417ceec175470e1c7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "d7e55dbe79c7d18bd284a363d77ac7dee1d66b8e"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "9446919d52cc1ffda3ca3424b0b8b27eaa1ded2b3310f0300dda6564df2a086e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "eb9ce80dfcdbf0858b1f4af7981ac9d2ecf7ace5"
os = "windows"

    [[LibCURL.download]]
    sha256 = "e64f5b454b73b60645bbd4cc2ac796b41e09205c128d1183a8ce3ed1a6bc4f10"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+0/LibCURL.v7.88.1.x86_64-w64-mingw32.tar.gz"
