[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "b8af834942bf697efbbe5517679ab62d9eb9f367"
os = "macos"

    [[LibCURL.download]]
    sha256 = "63e88a2cc196e5ec1b90b0ea396190482801875beccf7a0a69b80b59c32c5dcb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "d808ac2bbbe672cd85714f4a3f68b2068a63bca8"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3f490c3b4146a34d32b482b913523753eea07ac10e96a9c4975f8854de2cdc9a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "c3ea04ab09aa567325bc0eb69442a473b2e9dfb0"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e3b2ba31b6bbbf751dad2f765805294e3bae8d3decc34dc0ca99f571d1f8817b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "09a27cd089a0e00c7c2b917e38c58c8fb15e072d"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "b0cc991b6e5fd95cc54edbad65bce21fa85e50819dd6bbe33454168ba15727a0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d793cb91df82104dccdcdb6ed3e861e9a7a54ded"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "8f38261d90535a100d1c2f876dfbeb49797d296ddfe14973acb5e1d8ccb97d4f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db49c7a6f8007f7840e7ff25dc1971389323a587"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "27b595ef8c8fa2d494ca43df6559a813ad974c01e4581aa1fa3698d02f7747c7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c9d31e10c6e63ba1d5cd83c263fbeb15deb66af4"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "50279b314bcea8753433611b142520caa12f40c9b21becf24fe8bd8b1fe4e857"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c982a9d439d81b1e7ec08d6bc181657528f0730b"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c2dfea55727b9c07da15ee4e2bbfaa90aaea88389c47e8f51e3da2eba5c66824"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "27e935feaed84f48d2af0e55040807f7c4c71429"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e9f1deb0eab142061f83ab1fdb8393a0dac040ba2cb100238d9440e710d33216"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "a8b061ea7b1c2d11031acbdff5c3876c69c59fda"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ceb8d17f31be0590d75c6200ec40e256769181b0f06ebad50db1f0227f083f50"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "a1b9828461c9addf2e71d3f33460291555210c6b"
os = "windows"

    [[LibCURL.download]]
    sha256 = "df42e6a1ecef9c7be5bc1e58098748e272d81e8ab2c3768bdb53a12a5a50450a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "fa6803e2b308177da3f2f3bce20a41fe39d84322"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "daf0f135f2ed17063c2a7c4bde2e0fef089889a3220003e6af902131079654f2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "dccc19d9e97e05cf9a5847fbd6f3e382ec3270b3"
os = "macos"

    [[LibCURL.download]]
    sha256 = "ac5c9bc0be29cb61af542aceaf7e29e63eeaa3cad4998037cb9dcbb69a436cf7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "aacf2bb184e7c792d3c7605504b4e0c7348f58dd"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "426e38cf403b19ab7e57fed4247b8580d063de96433226279e40a875fa19751a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "11c0ed13ba708bdb8d2bf62473466bd95a6180a4"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "f9df7f2bf8fe6fc50d4b520a3e5c1df27fa4f8112a820aa8a40cd70150746998"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c066a3463fdf028fb27f78f1653673b447ca4373"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6277371acfecd13d936d16596945569015a2c753e23cb95b630cf21c48fa7089"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "ddf0f461654395972f91ac1ebb15f7997f0d439f"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "a963985668bb3ba20a2ea83f3673bb3caf323862c4e23a5148591b7ece0621fb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "546dced1394443d1f22325ef702a5d88787ce7f9"
os = "windows"

    [[LibCURL.download]]
    sha256 = "d5c2987f1cf18dbe3301f4179faebab37a6a47e5e5d6250ef6060f0a03385557"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.11.0+0/LibCURL.v8.11.0.x86_64-w64-mingw32.tar.gz"
