[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "182966becd0679a1c28cad2b07931e361d1868d3"
os = "macos"

    [[LibCURL.download]]
    sha256 = "447b921729746a57b7f63adc77caedd9e042270f2440befb2c47dfb9b8e4e495"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "6c96229c67e3c13c71c06ad783c596b2822d5041"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5d94a244d05f653e52ca1958df1ec00d6909545417c8da96eca0797b880273d6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "1e55a0f39d55eb6442e2a43c2b8098f03384fce7"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "325670d1be4b4dc6f655aee2b61bec430fa0a2c589e2964931820111913e3d76"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "61406ebfe95f2897b37f32e80b0ff2caa0c7d869"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "7394307ea3f7950bbca17d9c701dd9a98b84dcc7ed7af12491de0db9ffe25f26"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "379b4977b225741234fd517eac499603501e0b58"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5bd7afb47e9eb5d8d0ab4b8f96b251c6c69453e46a396aa3537ad93e0e60ba85"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ceeb653cc57b363d5775f567d59ec8be524a641c"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3598c6ad0cfd22f9e4a71a082a451c1f2198534fc4443ecbc551be5896c8fe1a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fcf7c9efd37f9ce2c6726989df1c12616b51b06f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "48082f21a05e93e55501f289e7a0a1366c1c96157a3ac5101fcc3ae0b3317e3f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "28c1d3f5187d6801bd1464737862e69dfa0bdf21"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f2c463a26f05de8b38ea2a394166e07cfee74fe9341b3acc7a8a32d92a2433d8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "9e10e5fb0d93f08cc5ddec9e0679a398d8a8ae76"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "51163a8f84d8c01296d2e1e40a9710311e9c7b7ac96578ae72e6bcfa6c15cf81"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "2b274cd8c39d2ce95f0faed6ea6126929a4128b5"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "757a8379e743cba23d89829afc6739a4143dfb167c47697761b5f2588778a60b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "d686b496dfefa7a1a0c176157b8805256757629b"
os = "windows"

    [[LibCURL.download]]
    sha256 = "6c76d282bda90ed69d5aae52f589862840cdc7a9226504aacbf0b8064428e2d5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "aa934d4238c0d5ea8589024bc4d41d8fd8aedc86"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "694842dcb5a71d248584678ac6174bff1bce80296e3669bb432a45b6d13d8c67"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "riscv64"
git-tree-sha1 = "e79c596d3ed065d6dd6adf646b7493b04e6b131b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "58ad89af59b13bdf69683457009de346b8355434d32efb42c61c7f0c089b0640"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.riscv64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c019e77abaf602fc308c5da4afe3ed7fecdde184"
os = "macos"

    [[LibCURL.download]]
    sha256 = "efc4b6afc1aa2e93824fee1e5666e08fc9e7de82d5fb9d1d7dcff5dc0ca350a4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "00161edfa07b74b84434bfeed13794d61b9cf8f8"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "568840feb32387e30e2632f6445c96003d3fb84c8ada3842368be061843ffb92"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "d73391d48d5b86f079c418c5d45477e0d25902a8"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "df96de4fa308d49e61f7383513684b2a8fd92c9a841125eb3715ca3cfe1243a7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "3a4c2976d90a0c5be2505d04e7bd7438bbcc0942"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d9161d3827d10a727e51220ebd5e0ad3ebec3e095d3e1c510e4188884b694370"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "f5ca8ba3fa9ffd207636bf3303a190d597c1951d"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "0b111b76b8636a0efc699e2cc1f9975ddb28aee583d292fb1150059d6d7a634e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "adbb92aaa6e5fc3411c058d4d9ddfcfd3870041d"
os = "windows"

    [[LibCURL.download]]
    sha256 = "7b2c917138aaee782fe2faa8442d8dacbb91b1546f2780cd07ce528f300b2fef"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.15.0+1/LibCURL.v8.15.0.x86_64-w64-mingw32.tar.gz"
