[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "8fa744b57f5645a9d98cec3a313996f4e8f42b46"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4611573a4001ab680481576d44fa99f26556accf9d0c9c3a85279deaafbc8238"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "eba94d13289b86383ced6198a647487c76935e2b"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "431a2a41a7ab230243c72bf48e3986fe2375d46c1ed64270f4716615b6a2a21e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44462aa08ddd437c3db510fd89322a70e234e40b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a8694c1089842a89b5e59f4d3fc4caccff9cf247c4669ea549432dde73d3e80d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e16a2bc7952a282787f25faae5b4b31b88c407bd"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d432a0d0a2b00f7e0057881b2245445309a8be418bca30c64d4f2b7e305466c5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "afac3e61c13feedad9ada2b283baeede10f62e17"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "2be73888217d11d44bf86423d88ca5edc996a88f9517306b1dc9ea13d6e5b7c6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "0e68aeef14518caf8360530a2b6376639f0c9e6f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "fea7b4a484f5b3781e6ffd9190ca56bbdd5431caaf9b6caff2507ba54beb0cb4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "c8d24b90fcee77f0abac8f36d121766857318073"
os = "windows"

    [[LibCURL.download]]
    sha256 = "b97c03db12558959f4e9e5c7f1f0951eb0963d321e2174df2ba9076ccedc5db7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "fd8a6eb3d178cecbf2f5f1eb0980c89538a2c888"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6e16b177d74b342b968ac6c58811ad3f20b4238fb855bb47e40e8ab8304f7916"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "68beb902cce74e834649268fe3a95b0eaa3887d0"
os = "macos"

    [[LibCURL.download]]
    sha256 = "a7c10a1af2daa75cb19aa41b74a681a8ce8e5db2f16c5395ae62d5685afe7981"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "020d352d4d0d89627aef72af3f72298bc4ad5c95"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e6fa501206cb7c96a35395264917409b37004f2f074eb0509ce1d4d0b976ac8e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "34f37e878b7185d1a0a6254765fcc736f6d9f91f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "41b0d1a0dcb2c92c79254c0fc88747b9a2bc213700450358328584d5ac732bf8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "65b45aa8c2d6bd34e917e2be57f271520c513842"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "e1c79ab86526cc2d5b960e8202a9335ba473deb634e25f0a76ba32a75133bae9"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "3f5465dccc316e68114290928944c315c0d60cdd"
os = "windows"

    [[LibCURL.download]]
    sha256 = "c3675eed2ee8450c455e0bac228b8dbe64d586efa9ee37423d91624e66f60df2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+0/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
