[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "c076a5c5338323ba41d9303a99528ccfe729698f"
os = "macos"

    [[LibCURL.download]]
    sha256 = "5d810a464c8219c386313ca8b4bae0b3ae30334087c9046692149b3378fbd308"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "159781eccd7dd7a089bab069896473114c4faccb"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f35d58c8156306e0de53db51a3c23f3bfc339c85eb71d90cb00f0973f1ecaa33"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "943f51b51ac28e5d4321c89eb2f42dd8222af156"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "09f29fc1c08916d1c0b2a48b59c6190371f2bc57e5971e4b75b71664f1716b65"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb3e4aa2cd234a4f5c32fa5873fd7c0ea7296153"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "8abb3fc6907d8e21f9638ada9957bb096e4607037272b7ce57ab12f44b6419d2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "64290d1934c631f12c72793cde804f72ff1fb73d"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "82f9d0c9b6e5caf49f4ef9ebe3d172219c0d8a82af2480a2f6308b55e5217f49"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "70aa1239beb9bdfa80b612615791ad4912411463"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a4f20ff921b1818137bb502f3389bcce1c8a43330c0ccacd59b593a463558b9b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "803b66fc982ab860ced767c0e5a0c12cae3939b6"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b14d3cce4a431a216542caf7f080b2c9e76be19f3dd36baa364ab84a8b26175b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "0de6e719b31269e35c10195ccb3c6a8ff6bead0c"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "20f84afe59ccfc98e2cb74dc5abac8b836f8b4db3a710b663eac8a6675a84072"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "0f4f14b8feb933ffb8ad4f4f13315a2ee98fc7d7"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "af40b38c1bc1afcf21d8b0cb8ad80ef02421aa6a48b42cc1e92bb2f0c8537be6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "f36c7cc5b691c10e61a3f0615d9fe8505e645b71"
os = "windows"

    [[LibCURL.download]]
    sha256 = "04822e89507755f93aff02ab58a64c977a16795b850f6f6c09c9efe9973961af"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "bdd1761eca9b4f0514a4dc51779036374e03acb2"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c95c21815c1aad85f0b509d474aa189d47b684284d5d6d548e0163f149c3d6e1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "54b417544cacbd03496ac0ad27c75a147b664a6b"
os = "macos"

    [[LibCURL.download]]
    sha256 = "94e63b3f6332d44d66e86c89591f7dd5896babff6e515380434ba3a548b61afd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "e605a66d936254c51d63d1a684c21de558fadffc"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a104466634fa7d076a1a9207eec0f7406958750ac45307681ad713b56f548a2b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "8f439aaaeffd5f4132db6b439bcf9aad845519c9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1cfdef4d799f26e147324a3329949c674ce1dea647832f40255db643dfaa28eb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "7bde674f52506218169335be9d43ce3247a836b9"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "d46810f8861035df654c6352cc0623819230cb630b0e6cc6d1bd2d9a9e1ef8e8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "784180722018e6dee8cb03bbd6492b25196bea40"
os = "windows"

    [[LibCURL.download]]
    sha256 = "f23889f566b60ba8d5c8c48367bb6b193891d0a7392d267ee8f36f21f3a80f38"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+1/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
