[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "e05ee77a67e521a33a959db21374baca90fd9ab8"
os = "macos"

    [[LibCURL.download]]
    sha256 = "daf53bd522065a6f983df47cc9997f90287732f957f724741d47efa4c2d1730f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "9eb3e46c3b07efa25b1af1e6c43e67c44702e68a"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5b9c0fc148956084343b3ee4baf5360dc9f024138252369e90c9edb3add1d81b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "7ed9400a75fdee88fd025ec3441972961bb90e44"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "34de5892807a2b8a6b4f168bafb6af6e86ea51c5903edec59715903e059ce54e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf1393513ad762b0e135fa5224e557993bce2e1a"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "7171e9e6be659efbd38389782d3db025f20a43eefb51d1ce9f2863d5a2781794"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "64f9fccbe800ec674f0724bed30fc158a162d41f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "93777b74ee6be092604961a48452de1184a931cc6a17dfdc37b1b484f6d426d5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36f04907913ede5eec3ebe6bfce8178ddc86a076"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a78442adc8f9716834c7d445966c9acd944b56f406f747fc4090ee90afc7d13b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "de6122fbc6b394fd1201c6eaecf8be48f386845a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "eac4503948b91f3527bf7a546315fed7de64e1cccc966a4fecc193b2405ba363"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "7ca6e737f3fd93733afe36d2b8da51d2cc98bbe1"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "40314bac6498c20ee830bcdb54e26a765d0b1f806ca3ea344ba184da47c471b3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "d900def5e6a6800807596b4209f7f5a580348442"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5ff1fb982647338560de86cf4045601790f5f35634631ec01309dc014d69238c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "d0538ea19bf76311289e41061c09a9497510f95d"
os = "windows"

    [[LibCURL.download]]
    sha256 = "86012adf7147b014a5c054d257cfcc3c723de46b433f473a1fcbbebbd912d3ee"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "08a5de259a7fe58dc51e8ab2ec263337bbc357c3"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0a680ad12cc571764f5e002f29da9566eb408a496a3dcdafc258439c51cc568e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "ccb7101a4ca0b3f7083092fe6df7ce6672ef57ed"
os = "macos"

    [[LibCURL.download]]
    sha256 = "40d12b68c61732459ee66536e5a5ef3b786f47d6916ae49633ed9768dcd58f36"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "adfcd2e30238ab5322a6a964c8bad9265e1a37ee"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "091341fa0ee1a4b3f2d8f2a2b61cb0ca3be04e3bada116411c8ecd8247f9f019"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "d668965662ebb445a388a64c9092ffd39440d986"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "230fcc50619488644e0ce9a1713966dbf6f2970545d1be98df477d2a83cc64ae"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c33cc8de40befc2cca9b1b9a93739b5b752f8418"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "329d8507dbb6bd252f3a7fb31670c3c2e47975b5ed0d426520d209cf05e7f839"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "5d565ce62d9a623c6b66b75618fe7388c25f35c9"
os = "windows"

    [[LibCURL.download]]
    sha256 = "271495ab3ea901ef75b089a26901cc7405fde29457f5b446800a8664474f28ca"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+7/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
