[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "c64c1a2a269af7251e266f9f5c934d750640a7e9"
os = "macos"

    [[LibCURL.download]]
    sha256 = "9fd3d33e5433644a938005e8da87deb1b2dfe0e62fbb4b38451ee85110581e1f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "d533b20fe8acd0058d42ad99cb46d62c3f124ed3"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3a97a4018f6e1694383ff6e783821ef29c8175729e68c38e1c4ad7530ca9b683"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "6fe41ea35bc5f7b633926b20cd26926e3bcd4ed9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "be0bd0fc049b2b463d116d432cbe345bac92f9fc4c70bb61e7ff8d250d987d96"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "fd3eafda9f44543856e4edfaed5c0fca39d97c87"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "8887c2274a2f1e68bbc292d0b49488aa750b7c5f79066f7aa830ce9e45d6259c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dbd4b48c9eb684913f81c724b7d7710ec99f2fb6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5ce1f6c2d5122d69812b2b42052361d6141e52cd7fd3f44b3727a6167b9400e1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05dfe33b6ab68b2f563712cedec39c65a3a9cffa"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "da75e2a7ed0add67b59f076cab4f48b8a7635300ef71ce396c654ee4cba162c4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da0d71f47cc242d016160dbe70d54a7d4d9092fe"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "755d1b254f70cbef690dacbb1d4f1169c33f7f6643b3e29a67ebed482b2a4f23"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "79d190704370161d80b60c765ec2ecf287c25ede"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1e7aa28f30cb6ea91e60cf61a16a106d01a78f77d96a7157c5f5f97cd317d65a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "188ebca616156c8bd224ef8378b7633406e0bbdb"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "522d44d6bbc8326c78119c80cfa68fc5a5ac93531fbe6e58cb7e0cc60c0b357b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "a5ceea62908bb5572288ff8e62964686f71abba3"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "fdfb927948ee08857d774d6807ac038cf22a4fe00e68b9b6f3718ce2f25f9129"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "574810c83a6dea4e136bd59000010ce77e13beee"
os = "windows"

    [[LibCURL.download]]
    sha256 = "dc62d07109a34f1ca43ba0b616f7d5aff870f990b0452d09e0d3d0c94bbc3666"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "9c95b7892abd9cc92f26239d06c37ba4c483b785"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "7625dbdd299b46f4eba0731c8df290ecf5872b7089d419c3c2b2931191bae7d4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "riscv64"
git-tree-sha1 = "cecb95ce909304628843c72f97217a486a380a7c"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "2176b1704c33bc58ae2f211b8b967e06f6d268c6501e988f251f3db1690bdad8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.riscv64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a26f36770a40b5909cbde24fc303e62686bb3009"
os = "macos"

    [[LibCURL.download]]
    sha256 = "3079c7b3e7eb5f567cfea2b4321bb80719aa3e286d538694ef52cf2d4702559e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "5816566e2f011ca9967631222323aaef1ca3d1a5"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "994a261c348df17de8f73b145d33a4a7a7ffd2fa3701344df9ac9fb1299cd792"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "f6cf652c3f4d66fd92b4a0f6aba8e62f69ccd343"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "3340b6edb33639ca2781b958101095c35fc31345fd5c38a05112cc70a1b63f38"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "38d5fad3fdeb254d2d17c06091d6833ef2b886c9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b4c695d3e77a0aaeae43d779d4343586af4afd2c18ec915082a7cc829b927507"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "e7fdb29751335719836b3b7e454d13793e537597"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "9bb9aa71c2c5428e24c43c28484dbcb204217683afa33bb35febd870abc0a916"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "91d2e4d8fe55895746bd22c000a924083a4c5c2b"
os = "windows"

    [[LibCURL.download]]
    sha256 = "bba5824b81e4fc62344dee1704a0b713cb642042f0db7692e3db6dbc4d3088bc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.16.0+0/LibCURL.v8.16.0.x86_64-w64-mingw32.tar.gz"
