[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "da4942f5de42b2945bd4ebc8f894f3732d4ec443"
os = "macos"

    [[LibCURL.download]]
    sha256 = "37bb17625aaf1a9ca2122368d4bd61aabcba382af4c8cba38033f1361dc8d268"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "3968e8bc4884d1644d0ee237ab1ccd93d482ffb8"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c83d77d35924cf5f26c460854e50d8409d43d8c8043b5475812b8eeaabf25385"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "0d38845b6b9fc0812050b61a8b541f11f17cd8aa"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f476a642c15d5a9a638f0680c5da02b1e5de91f20384a919139e44fb481003a2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "30f8563ee342835bd2bfd978a8d35265788d710d"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9adcb9db80a9ba1b7650b645a868acd04755f7d3c2ead752775a377bcd647bcb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "024be463f316f2b19ac4b66357bf1f4c60e72d5f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "811424eecb96aa951ff333781b97373c12e22fd2c06b0af394bf2e9574c0aea3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "61ec3f8d4926971d026dfff1e100fd98e3136e66"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "bcefeea86465afeb02faf34a523c777437a4632ed6dc3b947c597fc41f7e992f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "311825d5be79763491288e0d62723702947f90a6"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "54fbe360b76043c5dd74b3ca0cbd7cc89dad0b96bc867d601842351cb6b7e4f4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "31ff10acb92b5cab3aae0143786cbfa4abdcf0c6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "7c604a2653ea1e93afbc554031aa91c93faefb22e2aaa416bcb388585f1eb1cb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "5282bdfa24b478a72fa9434486203d6a638ba1bf"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9141e46bc9fc8cd41a29ec0683cc0a0e3f441dfc3cf29089194447fb5e650dba"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "63de5169e5657e7ee07f17638d686970c77dcd0a"
os = "windows"

    [[LibCURL.download]]
    sha256 = "ba9c90b430fa312242481bf18a5fa18a1acc28f631b3951e25dae769099392aa"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "14f831061daf46028fe6d09160986a54fd5279da"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ccf0bdd4bcbf107937a3331e9a36e1c085b8660f922e040b2f18b8345354dbd4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "332bb2c549c046a5629cffa3c62271d42509b0df"
os = "macos"

    [[LibCURL.download]]
    sha256 = "27479e2eefa7e1c42437e838df1a26b78ecba8ad883d8269011078d4ee7e281d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c89fdf1581cec4c29af44f2ad0036af1b5195038"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e339162759d6ab05403e44c65a6f6587297ca627a5342fd0a9e6a8705b61325d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a6f88904da69991f9d8fef153097994500217fba"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "8a4b7910b07892727ab6cc265f50a50235e1587ef7adfc6ca0570c261ffc9eba"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "8b8d4353b2dff4d1391595db5e94b0d63d3b86dc"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "fe986f6b34fb3d46374217595c4ba3ced6496e79ec13d870ea26f0b40964f696"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "4a6a1a92065cb6bd468e8f7914d61d9153325b7a"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "d997fa1199b5a402b3e3e8df2d406f24587cfae3225fddadd22be128177a9afe"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a6c3c00d863a4f92a639399447c051cf3e8eb73f"
os = "windows"

    [[LibCURL.download]]
    sha256 = "17042138a57839528b7d1c28486d38b11806dd1f59f789bb16cf5fc367d62be3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.87.0+0/LibCURL.v7.87.0.x86_64-w64-mingw32.tar.gz"
