[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "e04b50aff5bfbd2a96421b6e28019569022315c1"
os = "macos"

    [[LibCURL.download]]
    sha256 = "861f8e976579669732207dfd44cf752428a4971552626ffc3303d2e989a51858"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "99435ff530b174e5f724aa6df1dafa2db992b239"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "03c2696c68939fed071323e9af8295fbf84562354d9b638d1b6f1e1fb8eaa29a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "4c5a72ccb3325aec9dbeeba76377f60fa6e9e870"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "27260ccb68c29e7258a1911d66469ebbf9acf8c7044e9df85444fc71326a9385"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "38e825c493e77669cd7ff61c6f0dd0a82bfa5008"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "25e6aca4fa11ceb5c2430bd93bc229a79046e7ec9b3205a3a8f97b3345effbb0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb9e4f4ebf5dc4ec1f0f495f039392cd9a1852ad"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c9e5f0cb25d1b8abba0418dfb84b3f7a821ca2679570c1b533914c28aa834acf"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d49ec777c4bed848909f43d2d23afbe7b23a2a44"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "54caeac2f47ee4b804a169f9dabe96827a4a59b43f8fe53556bfc14dada02168"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54cb9761e11682284b9a0293454b1eb00b692c92"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6b93d5d2205d1bed205b92d3cb65d4036b20b17f21a0832c58ac243edceffceb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "941b18a682d4e6f509148b55b2a88d329be5c4bd"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f8f0f17f3d146a79fa946fb02295e4f48d61087965b2084d33a2e6f451a4180d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "65148c5166a51c558fdde8124e1114346006d972"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1b593fa177a4c8b337a8a42aac1397b9a86e0b3c1aa971dd77f717460a77ed7b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "67a1298651d3111bdbf75cdb222992386f15baee"
os = "windows"

    [[LibCURL.download]]
    sha256 = "72172153a709706f9c9231283465660e45a196e8af8372f9dfb316b3873b82de"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "7935a2e1bc860e9b1792d56716dba54009f71e8f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a2042090326c9f36f3cff802155e9b18beddc379e88ed931f774079b72a91f8b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "bc6aa03586e5a7514d3a48518e5175da7341979a"
os = "macos"

    [[LibCURL.download]]
    sha256 = "61fc546a7cf6da57a2e1914a004bf074544013603a01dbd64dfd0d30d440963e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "987abeee1b538b19bb506476319e47ae1fdea638"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "dba2aba02ba45c3322f55b4f568233d184485bddb570e4e3ed28ab3c16456426"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "cd6249a7a4368bce9da33bb9f0b0ad9548d74022"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "22208bdbf7594c3d90f51b79e37bcf3ac670a487c3a82512ecff3c37f28d05fe"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "b8ce53ca45c91790bd852c4f032f8492a5b3e0b8"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "ac77b5356050023804676acd5bcd5c0271ab0cefb1901a4bb9b7ae86803277d0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "da4b6ac80e495c579013835497575ec3575401f3"
os = "windows"

    [[LibCURL.download]]
    sha256 = "f68f84f3dec53cddb289a9da6d74373db15928ec8eb839845c0097a34c5811a0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
