[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "45a56d5e9c00299de308a615e0ee3adf5ac55452"
os = "macos"

    [[LibCURL.download]]
    sha256 = "2d1bc302e8870f962cb66997d0bce24ee745f67ff783c33a5cb9e66809855f82"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "c4cc8ab2566aff767890c91704a959e67af7e7fc"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "96496d3441ccd405ebc28f239d8af78e97131a862bc0587875ff3ea0e5f4c69a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "cce5d14d93ee00c1ed6042727150cdf34eb3cc2b"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6756e765231a1b5e44d7a3bc575c146876e73483f73186289a3b721528335c80"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "612bbf0c7c4214eeb93ff9dc0d820b17936f5969"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b9854d75df0f80519ae8835852472f73f9720558151de5c2e449feab08c334ae"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8293543d1bf3793257f3a7e1a19c2c9cb8088199"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1f1532609c2cfbd555d4e125b2e2161ba17f81ac32dc175013ef229d1c4ae110"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "65768d306440e10e29a81eb3e3f865803fa12687"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0416cc39e1cccfd4bdd1a8fc75d03502eff816d795c2b8b827fa53156b356e7a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fb94b30f1b7503356a3cc96a07edc3e54eaca7e1"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "de9543b5d3787941ec76ef97fadfadbcb074ca49b419a98ee5e0b910e8bfb3d8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "7fd56337a8e1ce2c67e0585a014f9bc615430bbd"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9cb1c57704690ff602c4b99127c87f245bbfa5a8f6bc41f929bd2a2089bdc5be"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "b146a3090e49359219e3dd09a018f75218863d16"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3a85bb14669a36213df784cf20b78b671744c9ba3ff59a4f378a5c8d58f69c21"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "20cf2b509b270fffa8926d4936b38be40efec5d1"
os = "windows"

    [[LibCURL.download]]
    sha256 = "b19aee9b27f5fcbb7e5efa05cd5ba41db915e17f4fa77ffdc623ad4b9b021410"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "3e4394a13b056a7dd8bd83c2c7c290f6f7a3fa33"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "721bceef3c5ca44886e0743b4d8b26ef59fefb56f38d237eda7bad327657ad4e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "47446c44b886846fde5055cddeaf015e6c4f9e90"
os = "macos"

    [[LibCURL.download]]
    sha256 = "7ac2aa006385b790c81ae58be3d78a2b81990f34d46bbadeae0cc58cebcd19b3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a2d0b6e272b2575c80fefdc6b08fe92681a9025c"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e56d08573eb8d4571023c2e46d1a2e664761c64e91509b0f4b90de1b043cbc52"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "ac3c0075e9d8f9c938e9e8854493150fab41d53d"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "beaaf261b78a4cce15be18ecd0a48e87a0f3b08c0f2db0395c62fff554377094"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "10a97b56a0749e519edf776ff98b573af446e47f"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "1cc0cbd145d6175ea7b177ecbd52c7cc9d4ace5df59b61f4ebb6c49f2c5b29da"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "dbd99b936a9803e382188eb8a0d13120ce776758"
os = "windows"

    [[LibCURL.download]]
    sha256 = "f16a776bec69c11eafd57a9d3e259d7a582c2c161c4859cd1afc07d925ea492d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+0/LibCURL.v7.84.0.x86_64-w64-mingw32.tar.gz"
