[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "28386b8f4a403e6eef4bc24583f2ef345b2e280d"
os = "macos"

    [[LibCURL.download]]
    sha256 = "b09efbc2284097fe010e3549cc668793512758c763c6f38496480426d527be54"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "db8ef237ba16f049a52d5c039efb22c43872f623"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1473fe718e83afa4155f2d6fd07a5fd9b2e1759a6dd510c87a1c3dc0d0f935a1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "af72281a4b7ec120dbb170a078cafdc2eaf9570d"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e6b08e3411d21c5f0464590572cb7b24a2cb79f5ff366d729c197ba0c01ab2c5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ec399ef5ae28480af470cdab4b8c6cbf487916e5"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "eb03f77e854ae2b936a72e1620f282096b559b61920703fd7dfb30228f152bdd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e5fb53f75cc17c74b7da96bcf7679977af5f8688"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "bd3f0a51515611ce0807c256d647d07f391a4781214c617f2e0c3626f0bcf65e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "62e8f7757abb09f6617e2506778d651d41e4090f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b5a5737cb7357dd33e0d09fb454a68339be7f4fdcbb95211b416fe154bba6454"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b53838fb92f6c8f4d09e847d27960875618378c9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "bee100829ea55da57d2cbe20509aeb8275ede9e9ea040f0b4e81c703d2af54e0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "efe26c92302c30cb974465578583e455e45c212e"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "44ff2e5bff5d849bae96836b6c25feb34eb6f1213805ebcb6bab4bfefe7a32e3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "3795d9a28062ce1728b8398426fcdf192417cd7c"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5a3dd12ad101008dfde5b21e9b9a4b27835fc095cce17407322926502c09e31f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "1cfd02778067a45ec430aa287b136906adb06359"
os = "windows"

    [[LibCURL.download]]
    sha256 = "7765b85d0f19867ec200fd33c0cb1ad72d8f72306194971ba6c46983bceb176c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "f18a8aa4637a6733c6de874babad24daa9d36093"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a9b089fad3c41b477c7686cc97fdf5f4d72a2145c754299ec183c2835a90fdc5"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "07fd4a8544d45e531e6a448f0d324fe7b36be4a6"
os = "macos"

    [[LibCURL.download]]
    sha256 = "d55a97ee16bd90d5ebe5b4bca6377537f5263cab3052c5a53c406cd505437d1a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "cd8cd790e2d46ef76b57602fb780b91f5351b967"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ab6ee6673451784b632edb100af968dcd58450e9952a5a18968d773d1489e045"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "6196a103f576a9c034721c1c13c47348945b2bc1"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "86db2b2d551dcada40c1c79afd1d4e6d930921ea7922f00ef6c8f328c61dea2d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "73a08cbda99ff6ffa7bd3cfecd0a8f2e68898f4f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b48c9923591791d39bb92ee33e654aad5bf592ebae66e0b6b637401253acc6ee"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "fd36bfeb59af0bbd6c8818f72e9d58310a930292"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "9da0f9254a1f5dd7e52838ccc17a65649d81577e5ec4492edfc532f1da55ca69"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "87a396dfa552b8ac46dbeac6f2811b3474870652"
os = "windows"

    [[LibCURL.download]]
    sha256 = "ef79265680b0e55772717d989110bda0d785c6950f9e55cd2ef34bb6f04ce74e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+0/LibCURL.v8.7.1.x86_64-w64-mingw32.tar.gz"
