[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "28386b8f4a403e6eef4bc24583f2ef345b2e280d"
os = "macos"

    [[LibCURL.download]]
    sha256 = "b09efbc2284097fe010e3549cc668793512758c763c6f38496480426d527be54"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "57d6637f906033232eba9906b8fcaab3be37a266"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "fa74554240e9e55360078d98d68c18a6901f4ec41902c8bae82499b6055a8b08"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "7b22a862f0df72f965c73eaef9c31a0709c0dc90"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "87d85caaee707edabe7971773b9620b95b50fe8dbbcb52b358b0f8c3fec35dbf"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd267981f3fde81db796ab59ff24322f411dddb5"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "33654a32db4a1f15c0d248c868316b72fc7d9d4a53bceda269051b0cc1473c3f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "190956cb204013b9985bc063f8bf15f1d918e8eb"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d3ef7adfa4b984e4dd4f9dc91dd745b84179dfeeab9f066f3a6af72a7861e9cc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6a3ab642bc6bf7e6db2c1de4102e42dcdd45f7b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "bad32390ae031f723228b289159635c2e1cadd873a2bf363121b1e3965ba9876"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3333dbf222c838a0104ffad6893e43d71b53bb6"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9b3919eede14f3628fc7bf2e3e7d121779cf78fca617a0f6f3c7c3c1270fe24f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "ba40c061d387f4a8a2f42aff307d67548fef7246"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a006f5aab058173db2dd285ff41d3fdeae6b4afa68b08afbc38e04d7b83671ac"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "c36f478bdd82c42ffdae54e8efde60a333609501"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "17f2ad8680b229f59d9283ce9d8fba85789c50ab64371f6a5bdacb7cee10a109"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "a7cf20e81649b7668f9578c688fbb27332a4606b"
os = "windows"

    [[LibCURL.download]]
    sha256 = "248a293fd93e6d3978932c321487637082fdcc963ca7005dee7721e87cefcb7b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "b10103ae250283615cc14664d0f1887b642802d8"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "066506e0d9b8e2aeb8f51262cdfb23db04d1dbe093a60448ccb9fdec0abcd2a6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "07fd4a8544d45e531e6a448f0d324fe7b36be4a6"
os = "macos"

    [[LibCURL.download]]
    sha256 = "d55a97ee16bd90d5ebe5b4bca6377537f5263cab3052c5a53c406cd505437d1a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "1caf1027e309b8cf9d631c5ffb6d861dd6ff7cb5"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "112e687b1f33d7103797f367c04071c3563f0d60ff9cb104f548866e9e105bd6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "ca70efdde9fafaded4248a7bf5d62919970df8f4"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "2afac7f8cf89551c61927c70cab48f0b3139e18fdd4ec5fd8066740f225df5e1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "890fe8351770448663c4a19e06c6fa7ea87431e9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f516de2a23796c49b00604ee51a7b5718ebc241920b5dfe5872e144387c4ee44"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "47a298afd67df47096aee94709326c266e3a62b7"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "bbde1e0be600d6ed0a5601837eb6dbb7060e10925c6721d8221afda38208db26"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "87a396dfa552b8ac46dbeac6f2811b3474870652"
os = "windows"

    [[LibCURL.download]]
    sha256 = "ef79265680b0e55772717d989110bda0d785c6950f9e55cd2ef34bb6f04ce74e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.7.1+1/LibCURL.v8.7.1.x86_64-w64-mingw32.tar.gz"
