[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "bbe775cbc53fc70bf8860a6f5e271041ccbe24e0"
os = "macos"

    [[LibCURL.download]]
    sha256 = "96b02578420431feaf7c721bdc4418b0b7c3a6b42b301e2c87eb220e0a7766fe"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "1f3e856994279461598445bb83e3a436cbc39c85"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "82597bfe5b997b8bc44b9abcf93aae39aa734377e37564fc89964184f4d7deeb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "88203013e767619bc5095196f33991d29f8c22a9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c6e03168db97ad7fa13d03fc82405d35bf5320ed4ae040b941b0faaddbb3a3ca"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "7f5b05834689f4ef1e8988a7a0c5da65ff4b353b"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "725631cb30b22aae696d4fd1ca1db1cc3a466b0ec69cffee08f1f5958f11fa7d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aaf879590bbdf7ba01590f6a9a176cb99b9dd2fd"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "81ecc5fc22d0cc00f954f5684caa6592c26fbb8ca0d0b94c225efe51341bc089"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bc476629e9bf24abc0a4470d940f2662dbc941f1"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "cdc1a917be2d1cbaff925c35c11dceaf90f7ea52f53ddb9fcc23d78e5029b92d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "de0d20e4b2f3681f52b906f44330bdc91c06e41b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0f8d2ce06c79ce9a625b5dc1d22b25d10d27f9d7635eca53e13c0e905a2d2cbf"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c990148654ee5c18951c03f42f4d4ef908bb1cb5"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0288d86ef44ad48dd42dd34eebf911aed246c9fe8c48b7ce33a6d5763dfa2c8e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "a30b5cffa90b15b94224e7729bc3af0d260068c9"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9e0a063acb64f4266fcb47665014da58ea91251dfa8b8290cf30fa30e5e73ea6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "dd1c4192504d12fa20e07712752b9b5ba1699f3e"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d04ca5e14c3adb054c126fa92b7fe85b45abf1bcdaca951d61ef056529c3d14e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "8fd1f2053502b6a676c4b00b68f746ab3d035901"
os = "windows"

    [[LibCURL.download]]
    sha256 = "fdf92b2e3db9e28ede283ba3e3d14ecea6c9c758fc2639cbecb23ddb3cda9031"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "230ca950545610b73f0c65eacb7dfeb6abcaeb15"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "29382a923bb10c67886479c37782bf2d4e8b03c26bac62a5fac14365823cf55b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "riscv64"
git-tree-sha1 = "7c11d8d0b134a92038da7332d27549f50bf26c66"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3a311284951e569be9a0c7b7e340dbe3055d9488460b5422b33cdf324b11da1d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.riscv64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "560f0743364aedb08ebe04be82fb8effbf04515e"
os = "macos"

    [[LibCURL.download]]
    sha256 = "8abf226ae080c9bf26570442facfff39a129afd69757a5a4b9b4ce3e3924fec1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a36e00021cf20f3c437e361d6013b2ff2baabde8"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "364ab15063b81be3a1d07cae38a03a43a7608d45c7dbd5dad794ebc4e2887439"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "bea5bcdae5cb9790d4f20297d6f834759096e1d0"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "014a940fd2f9a824663352f5f6d9052e1ea47cdfc4c133f9957486b2114074a4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "cbb987adacf4d46dd92344eab5da71840251f465"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "773b3e3b6a0c1ad2f9c3ac3bc64d77b8ddde531e99b555f2e429c70fc20b38af"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "100aeb449fb767ebcb9e13b0030102228becf51c"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "8ac58c2a23cc0043f1382f21e220fd476df873170416bf8901466178513c71dd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "9d3b0beca9d59f6bb1b026111cdebc1033769ed2"
os = "windows"

    [[LibCURL.download]]
    sha256 = "b1acb36ada0f0e3f31291ca964a66b7a86a4cda1efce47410b49fb7b700bccec"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.88.1+1/LibCURL.v7.88.1.x86_64-w64-mingw32.tar.gz"
