[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "feb7a6389da3807527b888ede0acd03a2c662ff2"
os = "macos"

    [[LibCURL.download]]
    sha256 = "ae9eaeae8a4ab722b46ea583a8cd576357ea91186ab6e20da12e6aaf9161f83b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "d752b068e3ea83bae07343fd9ac2b34e019b33f5"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ce41bce4a1b93711fe72ebdd581c16231935670205debb7eb604a2c9d5609594"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "4efe8104d4da4e723c8b097e8303f4f6b622498d"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "31de8dd4c516bc298872c0b474fd34767569b5401590092912873db27d13c01d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "c76721b9bdd665278ce1a34f0690d0e97c8deb00"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "77f76ba2b5fbb3fe47c859022395086a41708dae803346657f6cca162153e59e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8ecaf44a995f7e2059260881c3c1fb91c7a1da30"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "2d54a007c7c262df22ec27f31242b3a2bb34181c8bc4270845f6ab9cbaddbd74"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "54474612b62138c1c3abf7cf633c9f1289b07b3c"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "22fa45636dd364da4212f1a1b40d4591bd0fdc0307118555cc7ebd1c4a6b6a43"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a0095c5396feba8f15e09662c6f4080fa5b65dc"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "452d86d88cb0f391334df068e394e5245b81efef804a77183a736e6223136889"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c18eb43a0d3e3c1b7e1228269fb666fcbd7a3740"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "09b44fae5728dda5cdd6adc64e4e8efc1f7c150663d2d9cd90eb65c16db5a813"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "ea489fa628122db04e7e6e347fce9c533b805234"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "97caf9306e21b569b7f69dee07fa0f9d93798de69328efe61fce6051f7711e94"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "88e9e856aaff20f5aeac0691da6511f4d2763048"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ccc8789a9c2e8f66cefa6ffb9c0321c78c216aaf2bb108a61d82a673130adcbd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "88d66fda807bd90f54a213215b2a2556a5c93feb"
os = "windows"

    [[LibCURL.download]]
    sha256 = "45da0b0d615c875ca4687a7b236d0b8ec39a40dc8f1d2d6248f233f57b7c4e81"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "acec00512a883c8f57ac18f70021001ff05e0432"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a4368e65897cf178ee3e4c3d2d0076a86dc1f8feb1648d6ae8c3dcd1a4c2fb29"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "riscv64"
git-tree-sha1 = "ecaf4cdda70c3b34701f31513df6aee8b6b64bb9"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "dae47c81bd6fc3794f70b9265fb0d1daa53dd80536c19ac153d7503208f59226"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.riscv64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "de83a266673da96b64e6c16d1a376dc34bd492b4"
os = "macos"

    [[LibCURL.download]]
    sha256 = "5cb41d90dd337027fdcf6ac5ae412eb0f509c65b9a44b256f1b8b35183d4054c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a726f451c87d1854afb1c6eb12dbac10ee7c03a1"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "84181c0485d09ba57f09d759adc04976b6681712b39328bf75f2e59c36dceaff"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "66afa0fb767da353f5c302ec09f9d83507c4e9ad"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "f0635a0f41a407e5eda2907323eb357f0a687c8335e05f1565bec1d8c0dbe1ea"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "5e07eab5fd379878f25bc2aef73e1c55e64d38af"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f526a144626ca2af5baaf444eed191f64c577a9572f98a7c231cef0bee74ae13"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "bf42a45fbfe39b0ae3c4817aa387872eb14c433c"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "0c77610c8b664446448ec7607c0c66cdf4bad105a1ac68e00c83c0b86c3063f9"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "0aba6717f158635390451a1bdda382e4ac1f0f22"
os = "windows"

    [[LibCURL.download]]
    sha256 = "58b2365e665fbecbd8902e7c08fe3e1f26478b14d32a463241cc577a35554d60"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.13.0+0/LibCURL.v8.13.0.x86_64-w64-mingw32.tar.gz"
