[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "33922732a41606d299d4353c4716254663099932"
os = "macos"

    [[LibCURL.download]]
    sha256 = "422c24cc23e96a8355b12aa31c7d32ef590a26a9f3016b5859c3b67eae9dc56b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "0da6f3c12a4408b866771032875385297051400e"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "46c605f33e0ca6997d7255051f4b05f89aed79435b30194c2ad446bd53442dc6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "cd0a258b2fd323a0aa6a83ffc1b467471ea9963a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "aa0b9192413c1d77ee6b1a49ba2f2dd7c46b789a3dcf7ca442d2153b7abcb5bc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f05c3bd81255da0fae1ef477a63179c07197df7"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ee16e07bf4f6ce4276e1ad0d0898db655bc417f8cd3021297acfd5aaca762734"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "293fcb7409419882f9fe23e81b406c246ec149fd"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "8db8aaf5d08f6231dcc1e581be5d02e37a6d4465c06c259f4a18128479644705"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c51b2a880a697734c4e45827479a1ed31ce175ab"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "cb25e584a6112611935c8108e981d9b4456477703089e32aa4f06f446ffd3fe2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3502fa2ced090d9ee532ab4c03326fce97ed6bad"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "8a23bf370a25fdcde574cebf9659875577c4ca19860075697066e37e176cb26a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "f46d737bb3af2f7f488274a9cade05183435a23a"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ba4fc75f02a59e44c192545a5473c9f14ca0fc0194159138ebee91101dc3a414"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "8e023bbf2052c17b66270e4178068de32334322c"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "85078c8c88d2a9326e622533d366fdb7f3944b2c59ac6e83bd3daa8f34c13437"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "c170a516d80005b8540bcb30078af3b091ac86ac"
os = "windows"

    [[LibCURL.download]]
    sha256 = "a81190dd4466c1a73616fe131b0b2adb93e8cee2b32bddcc06aa9c1a6653961c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "e421e1921738ec7afc77d9a412b9f5bba392abdd"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e28f46a38ef6b80eeeb43540a17ef4578c5e3c5dc13e73bc246defab48a0f2a2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "daae19a36f8832f1bc1ed3608b9935d912479bd7"
os = "macos"

    [[LibCURL.download]]
    sha256 = "786bc42f65250ce7a4e65796cc46e025e32a985e1a1e3dec4d55c8791b2fc74e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "1c8af370e8119f1baa30b95e0c2c735ef160eb28"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5dee0ccb7f4c721d3ace1cb59b4c3c1645838dd9627c1b741dc18dbc9cbcc899"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "ef5c656f49c5930c01f22dd8e90a1a5d13eaf0d6"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "53c9e344cfb42ad8350557bb43a4f2fbf47eace1597d365a9305756363ae00db"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "57d5bcb6e675aad3fd0724db5796048ede26f227"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "bcda2b891726f368b8618d701613c23c398c7f50dd437d5854d0eaba9685f508"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "89375717fe96ab617cd5a8b8592fe2ee549eadf1"
os = "windows"

    [[LibCURL.download]]
    sha256 = "bb1f381095b6075bc2acfea4e07a1b0cfcd79c15ef298c0bd247df375559ead6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.81.0+0/LibCURL.v7.81.0.x86_64-w64-mingw32.tar.gz"
