[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "e70670e057ab801f4b4b2b5f3cdd35f6a806bdc2"
os = "macos"

    [[LibCURL.download]]
    sha256 = "330e60e2c8b01e7c409c5fe0f260030ff1a6e2c1dee5b9599c36af21d78c5cfb"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "db0e4b85d587f80ba2fa603c14ba3def1154fa13"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ff7725dc84ea94890812b7a65613f520c2edcb80236b4064bd173120852d1991"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "6410c506737098c213093bd3d75d5e6232e3ed72"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "45c557334dc8bcc27927e59adb820835b1387cce91a0dd8cd9602c52fa57737d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2da744fa56de914313972301907227afb147faaa"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3ca6781a7ccaf53c4b6bc94f6a4002f064127dc91c16ab338ddb4058390a5287"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e5c358fb30a278b78b90952eabc5f5d5424268f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a30da5005e8ca97f72994eb189064bbe7431e28caeee1da2ce74d6d80aae474c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "725d47469a79d7d5e6d3b76ef05e2ac18c50eb8d"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4e9f924865d05167f6905c647f3f1848367fd0243aa713ebdaf548ad8d4e40da"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "10bbe465520e4964ff26334c67f40c5d165a80e1"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "06a27e8d2b7ec444c720d92ca6472f42736cf53b7a32a436cba65b011d15433b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "711c078cd4acac27e94011eea74ffc6ae30c4b2d"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b50c656c4248e1033a44bef5a27f772f6ccee1e097990bb648106498a5d48e77"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "02327502d2888eb995e24ceecd3b20d2540fbb30"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4ac935d44aadd4019c5613baa60ca11ff0bd070dde54e86fa4c8a8293081cfd8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "67e3d9f781576bc075cb748e848ee4c4cbb54e35"
os = "windows"

    [[LibCURL.download]]
    sha256 = "1a0b970ac85c6f90badc35a8f35431a0902dbb9fbc6e87140cc75e8a111c0437"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "fc8d723bffed49d0fea54621ffb34718544b4815"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "a03cee91b30c9e6918e4f7a7a818ada39fdbffc27271d038cb498f3857d88e30"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "6a5d5c8b2943a8242fe6c492c85df3abad8e75f4"
os = "macos"

    [[LibCURL.download]]
    sha256 = "b8949f7c0a282f343971654d5b141329a17145e827f4af48727821ffaf1bb502"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "0ff2d5ae42c798824249c5b6e2fe4ab1f27ebac6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "71457b28ae54a5d840cee9dd852e94a58bd8bbc8cfbe351c3b5886ac6d3509f6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "38f658ddddf783f6bbd67cbf3b9872e208e58653"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "3cbe5d15ef5d426b630582f3816c6d4d76b9456c5e7705f58c102087aeaeee34"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c6e42d38d7fa29dc85932c1da97ba393a1917620"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "52b230d0c92afdbe53a99df9423abe195e821d38f9dca3e55defa42e0cc30df0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c19bd892f170e19abb0ce8e591628d5af3f11269"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "bfbe9d20dbf78a18ab37c6973a32166e4fe340ac22c8d722c0a3ee06f8a3ecae"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "e43f24ef7c8868323e540644d8448eb602230470"
os = "windows"

    [[LibCURL.download]]
    sha256 = "87400b10da8f067b860bb209d669fe0ee20b04d7f12b73e42d9f60443e32fab1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.0.1+0/LibCURL.v8.0.1.x86_64-w64-mingw32.tar.gz"
