[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "8a5420de992ccf383fc15f280b81d3f676e5095c"
os = "macos"

    [[LibCURL.download]]
    sha256 = "398a3ea5ea22e845dd71c4c721baa1a055323c778b2aa8cf4bc06ec0339c94ce"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "127fa8186d4d498780b93fd4c40b93881623b89c"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "7b3eb6ca54ebd8612a8ac5a2a2edac1cd3c596039bbf3e671817dd91dab4a25a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "79b1bb54e728fdeddfca1ae877253545c95ad9b7"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4c9a17be94bebf2819db9a72babcdc8c6f12432e7d25889701570364dfb2dd59"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6e246487dfc670bc6d42d16789d0cd7670be45f4"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "cbbac1ed814fd5f0cf5099489e7bcb08fd6f0ca3eaa7c85ee14f1c66ccb6a309"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b5f5f1097aeebecc345213741bd86676a16153a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4aa9b74cf252e74b44bdf2bfe299f364b655587bc4c76b483931fb864ce4a41b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e1297c7ccdc980891ab2e51c014e3601bfe6ff9b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9b41fff1bc50d64ada7ef16c11a4a430f9e576b9e3fd12e0e3a2aabbd1f5ad6e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b63316ac13a40116abe77268005f7e48b8845416"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "44984e237cc31348c7b36f0f748588fdef76e6dfef095f3eb48259f5b30cca21"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "4bfd15444188a103536f0b3a92ab3d185b3769e4"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "cf06881181163e8834635510568f8ef23e9ca60da12880434634d1699b3c379a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "107b690f890fab852a41897a6de80577533010d0"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "448d2ca413697ad93de27655c037b2f2d799e80ce284d584c78fbe66a4a8c46d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "e090991ab2bd53a5295abb6bff970e589a990d8a"
os = "windows"

    [[LibCURL.download]]
    sha256 = "0345fbe7cbfb0f47cc9afba96a7d095658a3c0cd9a49388fa2aedddd2aa18895"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "095d7e9d99a7871eeea12f25cb73e29821a2407f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "17ede312f492d8d3a1dd16a92f5047b7fdd861decc1739d6a55d14c005eb3d19"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c92ef0c769b843b553bbacdcc5a873df1e5d0052"
os = "macos"

    [[LibCURL.download]]
    sha256 = "73483d22585a39084830ca8dd1e916f107484bc0ecb60f5504f2bb6b04567760"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "877cdb33f2d47f643bead55ef95f10a206bb8531"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d9ec2986e8847c926ee93613ee956e14df4c3e97d99022861585dbb72b3b1662"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "e297d7474a67aff443837ae41d1b6d1568d1df34"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4291c3d19dab0cbb7d700a9d16902118dc455930e0f9b58e3b6c0b46951f445a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "d4da436a30c271a734352a5cb283036a18ae3191"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "8e8e712a9edcd6f9b9920eef3615fc92c6df10aaedd18889176cd9bf5edf828c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "159d6df5494d79017dbce5f510b0dcfe80ef51e5"
os = "windows"

    [[LibCURL.download]]
    sha256 = "edabbb8a6a9b989bcf82f0216bb67bedbde9e2e67cb2390d0305c38bb0047d06"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.78.0+0/LibCURL.v7.78.0.x86_64-w64-mingw32.tar.gz"
