[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "d17279d23f927c1aa710c5d211fde047de64c3a2"
os = "macos"

    [[LibCURL.download]]
    sha256 = "5001e8fe33ac5eb5547f91a466cc0d4216d5604893c38de9b70d2cf12fff33d7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "63c01c768eb6acfea3d0b358c0dc06918764ffd8"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3c9544a44b21b659c1dc68a5c2edda380bde3ec56e1fb761639d11245150b977"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "340643cd02f4e80674bfceeebcc12ee8ce604837"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "fd4e4082db20d88badf8455e8c854fb1eb5bb8030e29c497d8c39ba438836e0d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9e5479c1106143217e524ebf8c7e2806bf51f16d"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1cee7c3672562d00635ed86156fd935bf2fa2cb3e5d20c7ebbbea84ebc39a9b9"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "289d2b8e9e43321621d3aaf395b84fe8a4887dbc"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f4de8da3de245ed4f4527702f7bcd8bfb9d2f372d434b2e20e17c37da6a5b34b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6974ba7c265d61f393d2a94fc30ba95849804a16"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "aba715401d35a5d13aa9f11d3a152867726252617b87c006d5633882f411b6fc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef2f55bf7cdaac242d6b658e7305338e0dd7972d"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "96d587db10bae8f0c22bbf624768cf853efef4952493341e4c7872cc5a824866"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "2895d075d0411dd458f564011c5aa1e7946df493"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "31042df56bc67b1b5c8c29f8a420a6359a836af29effb306359416b46faf222c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "04c781ac1e0964f590391fa1f31a0ac34fc725f9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "280c145cb5b8816371ac240360c7973cc1ca5becc6c70267090b0e7b47eba386"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "691312014217a4bdb3c7b576bd93a78c1709ae37"
os = "windows"

    [[LibCURL.download]]
    sha256 = "244d69e3e2ebcb67a2c102d2a09c1ffef55c34545e3641c64cafa4751965e714"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "c4d9ac5ef61cec8ae1d264ad1e63ac0d4181c813"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "14c62efe78b0f233242cd8ad4e81fbca7ddd408728306656b000463c781457f4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c8700de93978665275c11ba8f567d7bd56edf984"
os = "macos"

    [[LibCURL.download]]
    sha256 = "c9e00fb99a4f59c2a3d685c86eb264cd68667bcd45f2e5545a956919cf25d6f1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "93a60afc98da443d40485acc130e2d18867bf7d9"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ac96c7922a021026543de68fbb964c1430ea03c467d04fab05ec93fa4c43062b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "d52d38d9374863fe8c0d16ba107fc305567bf274"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "159bab99cc4355c5a699eddc0c7bf1cf425b55ffbcaec5f17453a952290743db"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "9f616da36c452541abe3afedfa5fe39d71b8e2d5"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "7f59f866d5f1bbdc4a526761f1d1e99270bb3542d5ff6c032c38722317499064"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "909b63147029041b0e2e203db56e47891c1a3c24"
os = "windows"

    [[LibCURL.download]]
    sha256 = "36a2022fcffdf60f76f42d2e9dd0f7269d657d4c3b5a62521a6669b8ac02da70"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.83.1+0/LibCURL.v7.83.1.x86_64-w64-mingw32.tar.gz"
