[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "2cc6d1fcc6512d638db2bdf23dfe62d7acb7f1ab"
os = "macos"

    [[LibCURL.download]]
    sha256 = "84aaf0890a01015dfa85b972b567a725c146cfd6e2e4fd40cf3d1d8c578289d0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "5ef1a0d4a5640c6623666894f7580120a2a1bb9b"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1169765ae63444d72425efcaedcf3185d6d1e4b876bcaad88a4ac9a4e2d66e47"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "37fda1fac7efdbf8b17bc87096c8b05e6f1d89aa"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "001a90cdacdd7e9a2b10af1e7e1ce41bc8d990a386389d942a12508768c3b5a4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "516fd52fa1868657d8e4317a04aed100649fa251"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d57cb97fb9bcc33517ae00395ae39fe69e9b984470c28829eb15893e6e180bd0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "478df1244496b376001d1bd9fce07a06f8d4f0ac"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0d65c1ec3d402a9d0d4c2589b3a0ed93c2461a4d8eb6b4df4e831ffc5cdc2b0f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "74ebeee49509571dc54f373c12db00cab5ca4edc"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "65f6866882ad695a0a76ee75fe6c47ff6972686d221d2c651b819ac02a8d008b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9dd59a54b5269901b269c528c9d620c564cf7a9f"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d76e183136a1cb4b9b65dd8adf554081db5ba11e65fba191d8b5311c3038e220"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "7e0b9c570cc84e24a7c3bb6f6a7d46b71fdeba8f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3d96ce1925a13bde4b5c827295925d50619009304c02db0799d127ee872d87e3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "ab854727c6abea633eec64a6bf48f94eaedb8229"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9d15f2e52867fc8e35ec4a8b0a275d5f72dd98594cee94669958452a98304dfa"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "cb9effc800d37b11168c8bcdc8fa19d3aec2fd53"
os = "windows"

    [[LibCURL.download]]
    sha256 = "93b8c4818e66f0c6e4e96546ef17ae33b8a543692b14ecc3fcd60449be1b0c2d"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "86d91b1f24f8db65bfa5bfc31c1099dfa344c30f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1c3d55f93cfe8c2d32b5d67be74eccc342e64f2891bebbcc15aed76f5d94820f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "a80058492a595f8b90c3c8d7648e3ad0b13744bc"
os = "macos"

    [[LibCURL.download]]
    sha256 = "1de1dc2dea5106bb688f226e784829664283381131f02c4a48fa3b5b0bed9f21"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "42b210c3b69ca66037d2d65f4037ca03f099ce72"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ed084463c118057e8a6625e594b31b9e946786572b1f3844f1381b9fd97f21e1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "3b067575c2401718240a3adf5c4a9a8456ebebc8"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "96cee9efe97afa4cfc148126dc5d83331d673e350354efaaaed7a5a03b367e98"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "b265a6a1fb3c19e4c9e25843a16316da08d56de8"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "20ce069ebe7f4769b8192a1c5fde075d5d9c4a60fa1d927168b8994d7b662e71"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "990e8572cc9306fcb430655cb379e75d0443d753"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "467019929b39f9246e6b45ceae95f5eb759d0cd5120e4f47693558a0c3e238ff"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "9a63b0760cbcf6d93f228b6ce82e01033dc02744"
os = "windows"

    [[LibCURL.download]]
    sha256 = "6b68d615c4b9bd7d15f6a0d77b2a2618af3f47961428b0378a1cd0fb8346f7cc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.2.1+0/LibCURL.v8.2.1.x86_64-w64-mingw32.tar.gz"
