[[LibCURL]]
arch = "armv7l"
git-tree-sha1 = "5731e94570453ac7af61cbf2aea57b173289992a"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d9625c5e86db0ab773e9dce0be295823e97add57563502614d0d60dce0f2a15e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.arm-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "792f5afd7362a36e6ebdbaeec292a29da863d539"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f0b4ff423fc3edfa3a1c8c3b1d916765fdee05e82867adf55f83c7aba644b816"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "d95d7b40aa8765c95b168c396173a58d9e466508"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "92f438e59c789c6d1f85efed56b8a26d0b3d2b066076ec18ebf60100b54197d4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "95ed979eb016869f0a21ebbe5990fcfd9c5cc1d6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b10c7e12bedf620cf345ab9580944ee9f90e66e0ee57468e4035bf5d78de1987"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "37daa7c81d6801b619da8e904b8a82f3b3ef578b"
os = "macos"

    [[LibCURL.download]]
    sha256 = "a49798356a38ce5ea2c9a9fb05a702766e466deab3481f23cfd72dca908b7e47"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.x86_64-apple-darwin14.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "8c820ad8f39670c1fd2d4f07e7e87dfcf8f40307"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "bef1f3f8c31952b18a1a9f9018ded43d918671b14843846dd25ff8793a123fd2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "aab55b4af1b5e509dcfea06875e654bc14bf8b91"
os = "windows"

    [[LibCURL.download]]
    sha256 = "198f4682b30367dc708f0f28fab5c3e8ff85cbfcf8d1f824586a7cdf6c6499bc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.x86_64-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "bd4fbba971b4c16c4ccd0d90f5ca8c57dbbe4e83"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "caca1f1611ec39d6c175e7d46013dfac8ce0f5d5b53cdef5ee7b23b1657dbb0b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "5cbaa5d2c3c05f8cb371090991dfd2970d0cc6bd"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b4e8bed54e591e82682b78ce769ec60fd8295ec00efdf8bb25d9f8823f572d01"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "0ed379ccd87f3b4cdba9a133f8e94fa3dfc7357e"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "94f073825c67770722607fef5cb28a32e5c54c9a8479c0ad22e0d847587f26ae"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "8591e5aa9245d61bfccf4fd5ca49dc2863a9f098"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "ea05921cefe331387df18794bb9502caeb99cd9e6f1c575ce96f03671e93bc0b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "65a9375e843e08b9ae928f6341a064dc442a6ab1"
os = "windows"

    [[LibCURL.download]]
    sha256 = "538895aff2300698b7f82c82ae3415e10b21002352b3a32cdab6aea2b3158cf3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "armv7l"
git-tree-sha1 = "503e25c85d4815970b900b8f781ba692df104ccd"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f2eaa5177cc503f3b78578385cfd895374ecd198e3b48cf6f2b3b2c443a8374a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.66.0+1/LibCURL.v7.66.0.arm-linux-musleabihf.tar.gz"
