[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "f2189321d5fa283dc7756742c3441e1a99ddfb09"
os = "macos"

    [[LibCURL.download]]
    sha256 = "2b3edc0c34caeb52d02688d152945481e4862370acebd396c91859a35e06b25c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "d1ae97e9ac44b0f23195603dea94d9c6a0bb9771"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4bca699670b25e0d343efed5a2ccb5aac531834902b7394e783c01172e21b4a1"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "48cdab929ee5c06c041fd1b0c2246679fdfc9eea"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "de706194acb12e8d2fe54dae1a390ca8dae5c3827591ebbe0157799446cc619c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "63b78845194e16b17782458e9521dd551baa507c"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "918cdc6759c9c6554f432c13c2b6ffc4b7cdc4bf300a05911a14b0e3c942b88e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "73a7e175626fa42243e459553a521d4ef2f2cd18"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "f08f6779f33346cef8e9497fcabcc0f73a8dba65e601a32c123a55b2b56ffedd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3a25257f1226552492cdfbb6df4916c7f267c8d"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c657979bd7c7765a5cee8ee2870562b47424cca051387bd2c860167d8a64a4ed"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cd78d1676ede20e4983ec44f541c5ae08c8809f8"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9d78b01323f2a0f5535e40960944172f690455fa0d69b13a5fc93dab1234765e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "838c99dac6126981b933038313995583aa4851a6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "aab1f55f8b655e5646f080f73ffcb13fefee848e84d84d30b600641ccf438393"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "0d7bdf581985e15728f827fcdc56f975d763483a"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "4a913e06db2506e97f723d06a751778239245f0e4fb231974c496fe3ed74bdf8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "c960aac2b1d917ad3b6183cc513a26427cdfeb39"
os = "windows"

    [[LibCURL.download]]
    sha256 = "c43d9f3230be2bd7897232c59b104e152d5f53695727b4a2e3785cac630f0f57"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "ef986223066309945e4ec10d8fbd56bed1541544"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "13cb797a7d0ad877a16a7bc00e3aae0962d8087717778926b0683f7ed65ebbff"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "48c085dc41a19ee19829c25880740b04db4fc839"
os = "macos"

    [[LibCURL.download]]
    sha256 = "1e7b83f773cbc768b0ff4e06e8f2ca998902d2fec5c47a0f6917f9403b727ea3"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "1553dd9b094b5c9eb58feb144f6da1c678d0a68f"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "3f583f8ffc6de8a54582ca49826f311ca3bebd371519ddd1e160bc48a4b45030"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "5a35a9d2f7feeb0833ce89e0ad19d3299da8570c"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b643df8d51e5440f2adf8e18642ffaf88aa1e697667b0aed876bdd754a33c8c2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "bd386c176d1bfe89202fda5d13c1535f586eb2ae"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "4afde05c3e0b0eb6e594030908ffc541bf9351dfc3d38205b5d88bbfd7d7cf66"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "6138437ba3a598813dd7dfcc2c650bd478792b9e"
os = "windows"

    [[LibCURL.download]]
    sha256 = "6e12ad2a5ad772d8c487ceb31da53e47fb34c127b38dcbe864801be2c23d3c38"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0+2/LibCURL.v7.73.0.x86_64-w64-mingw32.tar.gz"
