[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "07da933bdd9de1f0d269e650fc24280a016a4cc8"
os = "macos"

    [[LibCURL.download]]
    sha256 = "5f2990f3abb00226d59666173ad2cc408134ac8ab8dc7ac46e6047bb970e2576"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "181609966990315eea43b133b06c4ea064e136e6"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "0a121e8531529028039959954c7eed1bbeef6545875555343fdfefdef9b380ee"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "ebccccc6943301246c2816a2c7480879d82f1ec1"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "33f33617741cf7a19124e0a0a1d39cb5098e54c2aee833fd8d02e8a5e76ef3e0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "4ff6c2cd4b6ee7eb5f7d96c26429eb347bd8075e"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "cbc61826ad04535fcf9bade840c28d51137ce49468846c478fc35bb1d280f841"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.aarch64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "60fe623ba74665b22f8e1f735d096912652ed1a4"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b0754fd2371ffb2c04c24cf02ded8b795140c020ddac3ec766f687fd2bd0706a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87317a6ce18c4095604cb39951c7ecbccdb8a770"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "601996f115cc6a7961a70c41bca8d8248387517308818dea2eb946b32fe5595e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8513ce217761def1279be10aa6a664b7c6d1211"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b5c31da00e2a59d46c7b74956307ca1af12667a3137f8281817ed6a0ddc0bc30"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c05d9c31f54510c6f82a45bd19d666811747c10e"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "9806f8833df81e259cc10572b9206f065a03854af3d2660a4c151eb3ce2724cd"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "19d70a1b3251e8cf5856952f604dfb148ae7b098"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c9b51f9c9eb6fb944217a998684b91c0b4ed0fe7669ee57cb82401fffae09bcc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "21ae84a228b4841fc8cb2aa75276485d1f3bab92"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e549de0fdcc379b94fed1aaf4c830e65836cd0bf3020c1d3759d019780ed2f32"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "204e9c1d58b7224a23049291244b8f4bbafac4c3"
os = "windows"

    [[LibCURL.download]]
    sha256 = "5d0223c87ca0deb4be8cf977f0a9731a10d6a872ed730b7f586eb34bd7153af8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "fa2e0c9ff5b2b62abb0cc212f0eeeb8182446416"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "ab7e8cf1e04e067108fc17986c3c977f10dfafe0c221d83e0e493389ff748edc"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "riscv64"
git-tree-sha1 = "89d91fd01e31953fd8ae5cdce37f1335817f9f78"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e6bdc19e56235d138800a783cef91f9fc449986aa86a2a53fbc03b0a63dc2d8f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.riscv64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "55ebebca86d9a31481e4a185ee7921d7f15b5256"
os = "macos"

    [[LibCURL.download]]
    sha256 = "0454e6cb446ff14c6e107d70801db0d6892c17792ff69d4ead4a5a90d897f66b"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "1c6fa6f1642aee3b10254c50926fe502b9199b92"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "10a95d48243b290d47094ed58b93615296bf2862a9869789c91f413e59576372"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "03c744dcc6737e4379c1a593c968eb1610db27e3"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "6f28118b555dd4fde75facb05c4c4266c19ed4b67213896e0e56bb72adb48a36"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c3c303726e45e771afd401b03796fd18f264c1c0"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "26e83520fa2c3885db4f96a1636200ff25d3a14988d1be74e1a34bd834ca64c8"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "43b1e0de294f4b7eecfe40ca0c762ded56afb121"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "d1b258ae72a1e14591d7a8727e93c3654f4359b7e134ab8fb3e593f42366b8ad"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "cbe4350898a6ced35e8f4fec8d0a5e0a8cb60ee6"
os = "windows"

    [[LibCURL.download]]
    sha256 = "9b3766c76d4ba84be7cf74f9ac07a4478215bc66261147bdf1c502c274efcc9f"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+0/LibCURL.v8.18.0.x86_64-w64-mingw32.tar.gz"
