[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "711ee015a1210b20954a6e2504b0262aed324dea"
os = "macos"

    [[LibCURL.download]]
    sha256 = "9d53bfe5ca5e444c9781b45662f06c8b5ab15d03c94564ca9d85e3ee5768937a"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "c465c146eea052af2cf013ad5e65de80cf610fc3"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5ba81b8a78a2c8966e14763f927d45ab471ea94a86bd216bd2fc5c59c2fbe756"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "c290a0217c5069075efa026afd4691280568df37"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b3c605bb5ec74c1bdb78910165d98b76488540b10e0c565d30f6719929aa9214"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ffbea20098995e0c0899800e07f5cd9e54edf463"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "b8d8f1ce7dc0536bd9da5f3cd00ea4bb133ca3a834464eda213e02a57a744744"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.armv6l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "34dc66a8187dd10709453a7b7c04c2e0496a8e21"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "39a847396c67266515689acc043c45ed869a9a7245aca4b5cf9e6a3747b79b75"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.armv6l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3bf23be477662c4e0e820d4eb57f636a01e421f2"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "8d00792beb1d120ef7ca2bbd3f386e8242d50d5e5a053aaf838317826bc0930c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.armv7l-linux-gnueabihf.tar.gz"
[[LibCURL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e14567d39818d4f7114053e462e46665f7380cf"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d12ad7d03cf62edcfd16ec5b44c107d3530f2ca17cb023668a7e6bb440a9927e"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.armv7l-linux-musleabihf.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "4999459345a9e89b6a187d50dfa2755e3fc15b59"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "7593773513b97465e0eaefaabd3616095a6165a87bfb490739d320c273c797e0"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "036b0583dbe9066c5ea10c332e4b6375c71202d7"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "52537942e501f0cbe8d454056ff3057e163ba50e20aad371d87aab6a35a964e7"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.i686-linux-musl.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "d047414986de063c3dd630c7f2efb87069e6d0b9"
os = "windows"

    [[LibCURL.download]]
    sha256 = "8516f02033577716b3667172142a763db25cd9187aa8987ea99e880b65edf1d4"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.i686-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "powerpc64le"
git-tree-sha1 = "034d1da71ec5f8de04fa11c1255ed9d4f12c9c86"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "d160e3432cdc16a65ba5a4f96c8dc26cfa6631285c12043ec395a6fea9a2a027"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.powerpc64le-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "27725f3b58c6dbf41cf4914c53553c692478a015"
os = "macos"

    [[LibCURL.download]]
    sha256 = "be30a8a730e7017fd87e3e763c007496c41488dec62d9086a5dc7a348e8e9d6c"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.x86_64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "0596bcbdaf3f9f4772f1ff433d8845973b63c20c"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "c8015f9384099c7b52a224778b73edd7a13930953d56702b92b4fd5c391a78f6"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "6a9ec55cfae6904082ae910b8af5ea993f2fa62a"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibCURL.download]]
    sha256 = "6f0355cc65a137203a9f07b15788dc896938155b2472b18863a7f58842f7d737"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "38031b580d36aaa64ded135645db6510b4f97a57"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "83471b3f5d0839270ffa2adeb9b9887f0823f148810bb323b71f253300ae31ca"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c4c500d9c78f37979731e18f411049116b6139ce"
os = "freebsd"

    [[LibCURL.download]]
    sha256 = "5fe8cd562da7f438b2651009da80f36335f44bb535aa9af7a3a5726d0a882fb2"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.x86_64-unknown-freebsd.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "55a5d2e2a5ac8928ac00a4cee6ab5c856cf58d56"
os = "windows"

    [[LibCURL.download]]
    sha256 = "ebca41da3117ea9a224a43d204f2ff457fc8dfdaadc1fbc5c7445d5dfae280ef"
    url = "https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.84.0+1/LibCURL.v7.84.0.x86_64-w64-mingw32.tar.gz"
